-- =============================================================================
-- 003 — Historizar Socio <-> Entrenador ("a cargo")
-- =============================================================================
-- Reemplaza Socio.id_entrenador_a_cargo (columna de valor único) por una
-- tabla propia: Asignacion_Entrenador.
--
-- POR QUÉ:
-- id_entrenador_a_cargo no viola ninguna forma normal en sentido estricto
-- (depende entera y funcionalmente de id_socio), pero sí comete el mismo
-- error que Telefono ya evitó para los teléfonos: mete en una columna de
-- valor único un hecho que en la realidad puede ser múltiple (un socio puede
-- tener más de un entrenador a cargo A LA VEZ, ej. uno de musculación y otro
-- de funcional) y cambiante en el tiempo (si hoy se reasigna, el UPDATE pisa
-- el valor anterior y el historial se pierde). Es el mismo patrón que
-- Asignacion_Rutina y Asignacion_Dieta ya resuelven bien; acá sólo faltaba
-- aplicarlo también a Entrenador.
--
-- A diferencia de Asignacion_Rutina/Asignacion_Dieta, en Asignacion_Entrenador
-- SÍ se permite más de una fila con estado = 'ACTIVA' por socio en simultáneo
-- (decisión de negocio confirmada: varios entrenadores activos a la vez).
--
-- Este cambio ya está incorporado a schema.sql. Este archivo existe para las
-- bases que se crearon ANTES (como la de Neon), donde correr schema.sql de
-- nuevo fallaría porque las tablas ya existen.
--
-- Es idempotente: se puede correr más de una vez sin efecto adverso (los
-- índices tienen nombre explícito para poder usar IF NOT EXISTS, y la
-- migración de datos usa ON CONFLICT DO NOTHING contra ese mismo índice).
--
-- OJO — limitación honesta de esta migración: Socio.id_entrenador_a_cargo
-- nunca guardó DESDE CUÁNDO ese entrenador estaba a cargo (no existía esa
-- fecha en ningún lado). Para los socios que ya tenían un entrenador
-- asignado, esta migración crea su fila en Asignacion_Entrenador con
-- fecha_inicio = CURRENT_DATE (hoy), no con la fecha real en que empezó esa
-- relación, porque esa fecha real no se puede reconstruir de datos que nunca
-- se guardaron. El historial recién arranca a contarse desde acá en adelante.
--
-- Aplicar:  SQL Editor de Neon, o  psql ... -f 003_historizar_entrenador_a_cargo.sql
-- Revertir: ver el bloque del final (comentado).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- (1) Crear la tabla nueva (si no existe ya)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Asignacion_Entrenador" (
  "id_asignacion_entrenador" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_entrenador" int NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date,
  "estado" estado_asignacion DEFAULT 'ACTIVA'
);

CREATE UNIQUE INDEX IF NOT EXISTS asignacion_entrenador_socio_entrenador_fecha_uidx
  ON "Asignacion_Entrenador" ("id_socio", "id_entrenador", "fecha_inicio");

CREATE INDEX IF NOT EXISTS asignacion_entrenador_socio_estado_idx
  ON "Asignacion_Entrenador" ("id_socio", "estado");

-- Sin nombre explícito, a propósito: así Postgres las autogenera con el
-- mismo nombre determinístico ("Asignacion_Entrenador_id_socio_fkey", etc.)
-- que resultaría de correr schema.sql en una base nueva. DROP + re-ADD deja
-- esto idempotente sin tener que adivinar si ya existían.
ALTER TABLE "Asignacion_Entrenador" DROP CONSTRAINT IF EXISTS "Asignacion_Entrenador_id_socio_fkey";
ALTER TABLE "Asignacion_Entrenador" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Entrenador" DROP CONSTRAINT IF EXISTS "Asignacion_Entrenador_id_entrenador_fkey";
ALTER TABLE "Asignacion_Entrenador" ADD FOREIGN KEY ("id_entrenador") REFERENCES "Entrenador" ("id_entrenador") DEFERRABLE INITIALLY IMMEDIATE;

COMMENT ON TABLE "Asignacion_Entrenador" IS 'Historiza Socio<->Entrenador ("a cargo"). Mismo patrón que Asignacion_Rutina/Asignacion_Dieta, pero permitiendo varias filas ACTIVA por socio a la vez (varios entrenadores simultáneos).';

-- -----------------------------------------------------------------------------
-- (2) Migrar los datos existentes ANTES de borrar la columna vieja.
-- Sólo corre si la columna todavía existe (para que sea seguro re-ejecutar
-- esta migración una vez ya aplicada, cuando la columna ya no está).
-- ON CONFLICT contra el índice único: si se corre dos veces, no duplica.
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'Socio' AND column_name = 'id_entrenador_a_cargo'
  ) THEN
    INSERT INTO "Asignacion_Entrenador" (id_socio, id_entrenador, fecha_inicio, estado)
    SELECT id_socio, id_entrenador_a_cargo, CURRENT_DATE, 'ACTIVA'
    FROM "Socio"
    WHERE id_entrenador_a_cargo IS NOT NULL
    -- Inferencia por columnas, no "ON CONSTRAINT": el índice único de arriba
    -- es un INDEX, no un CONSTRAINT con nombre propio, así que ON CONFLICT
    -- tiene que apuntar a las columnas, no al nombre del índice.
    ON CONFLICT (id_socio, id_entrenador, fecha_inicio) DO NOTHING;
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- (3) Borrar la columna vieja y su FK (DROP COLUMN se lleva la FK sola, no
-- hace falta saber el nombre auto-generado del constraint).
-- -----------------------------------------------------------------------------
ALTER TABLE "Socio" DROP COLUMN IF EXISTS "id_entrenador_a_cargo";

-- =============================================================================
-- REVERTIR (si hiciera falta — OJO: esto vuelve a colapsar el historial a un
-- único entrenador "actual" por socio, tomando el de fecha_inicio más
-- reciente entre los ACTIVA; si un socio quedó con más de uno activo a la
-- vez, se pierde información al revertir):
--
--   ALTER TABLE "Socio" ADD COLUMN "id_entrenador_a_cargo" int;
--   ALTER TABLE "Socio" ADD FOREIGN KEY ("id_entrenador_a_cargo")
--     REFERENCES "Entrenador" ("id_entrenador") DEFERRABLE INITIALLY IMMEDIATE;
--   UPDATE "Socio" s SET id_entrenador_a_cargo = (
--     SELECT ae.id_entrenador FROM "Asignacion_Entrenador" ae
--     WHERE ae.id_socio = s.id_socio AND ae.estado = 'ACTIVA'
--     ORDER BY ae.fecha_inicio DESC LIMIT 1
--   );
--   DROP TABLE "Asignacion_Entrenador";
-- =============================================================================
