-- =============================================================================
-- 005 — Horario semanal de actividades y lista de espera
-- =============================================================================
-- Dos cambios que apuntan a lo mismo: que el recepcionista no tenga que hacer
-- a mano lo que el sistema puede resolver solo.
--
-- (A) Horario_Actividad — el horario semanal de cada actividad.
--
--     Hoy Turno es una fila con fecha y hora concretas, y alguien tiene que
--     crear cada una. Si Yoga es lunes y miércoles a las 19:00, son dos filas
--     por semana cargadas a mano para siempre; el día que alguien se olvida,
--     la clase directamente no existe y nadie puede reservarla.
--
--     Con esta tabla la actividad declara SU HORARIO ("lunes 19:00, cupo 20,
--     profesor Romina") y el backend genera los turnos de las próximas semanas
--     a partir de eso. Los turnos siguen siendo filas reales y editables: se
--     puede cancelar el del lunes que viene por feriado sin tocar el horario.
--
--     Turno.id_horario_actividad marca cuáles nacieron de un horario. Sirve
--     para dos cosas: no volver a generar el mismo turno dos veces, y saber
--     cuáles NO tocar al regenerar (los cargados a mano son intocables).
--
-- (B) estado_reserva += 'EN_ESPERA' — lista de espera.
--
--     Hoy, si una clase de 15 se llena y alguien cancela, el lugar queda
--     vacío salvo que otro socio entre justo a mirar. Con la lista de espera
--     la cancelación promueve al primero automáticamente.
--
--     Es un estado de Reserva y no una tabla aparte a propósito: una espera
--     ES una reserva que todavía no tiene lugar, y compartir la tabla hace
--     que el índice único (id_turno, id_socio) que ya existe impida por
--     construcción que alguien esté anotado y en espera al mismo tiempo. Con
--     una tabla aparte habría que chequearlo a mano en los dos sentidos.
--
--     OJO al contar cupo: EN_ESPERA no ocupa lugar. Todo conteo de ocupación
--     tiene que filtrar por estado = 'RESERVADA'.
--
-- Es idempotente.
--
-- Aplicar:  SQL Editor de Neon, o  psql ... -f 005_horarios_y_lista_de_espera.sql
-- Revertir: ver el bloque del final (comentado).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- (B) El valor nuevo del enum va PRIMERO y solo.
--
-- Postgres no deja usar un valor de enum recién agregado dentro de la misma
-- transacción que lo agregó. Como el resto de esta migración no lo usa, no
-- hay problema; pero si en el futuro alguien agrega acá un INSERT con
-- 'EN_ESPERA', va a fallar y el motivo no es obvio. Por eso queda arriba y
-- separado, con este cartel.
-- -----------------------------------------------------------------------------
ALTER TYPE "estado_reserva" ADD VALUE IF NOT EXISTS 'EN_ESPERA';


-- -----------------------------------------------------------------------------
-- (A) Horario semanal
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Horario_Actividad" (
  "id_horario_actividad" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_sede" int NOT NULL,
  "id_actividad" int NOT NULL,
  -- Día de la semana en formato ISO: 1 = lunes ... 7 = domingo.
  --
  -- ISO y no el DOW nativo de Postgres (0 = domingo) porque acá la semana
  -- empieza el lunes, igual que en el calendario que ve la gente. Postgres
  -- tiene EXTRACT(ISODOW FROM fecha), que devuelve exactamente esto, así que
  -- la generación de turnos compara sin convertir nada.
  "dia_semana" int NOT NULL,
  "hora" time NOT NULL,
  "cupo" int NOT NULL,
  "id_profesor" int,
  -- Desde cuándo y hasta cuándo rige. `vigente_hasta` NULL = indefinido.
  -- Existe para poder decir "Yoga pasa a las 20:00 a partir del 1 de marzo"
  -- sin borrar el horario viejo ni perder los turnos que ya se generaron con
  -- el anterior.
  "vigente_desde" date NOT NULL,
  "vigente_hasta" date,
  "activo" boolean DEFAULT true,
  CONSTRAINT chk_horario_dia_semana CHECK ("dia_semana" BETWEEN 1 AND 7),
  CONSTRAINT chk_horario_cupo CHECK ("cupo" > 0),
  CONSTRAINT chk_horario_vigencia
    CHECK ("vigente_hasta" IS NULL OR "vigente_hasta" >= "vigente_desde")
);

-- No puede haber dos horarios activos para la misma actividad, mismo día y
-- misma hora: generarían el mismo turno dos veces.
CREATE UNIQUE INDEX IF NOT EXISTS horario_actividad_slot_uidx
  ON "Horario_Actividad" ("id_sede", "id_actividad", "dia_semana", "hora")
  WHERE "activo";

CREATE INDEX IF NOT EXISTS horario_actividad_activo_idx
  ON "Horario_Actividad" ("activo", "dia_semana");

ALTER TABLE "Horario_Actividad" DROP CONSTRAINT IF EXISTS "Horario_Actividad_id_sede_fkey";
ALTER TABLE "Horario_Actividad" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Horario_Actividad" DROP CONSTRAINT IF EXISTS "Horario_Actividad_id_actividad_fkey";
ALTER TABLE "Horario_Actividad" ADD FOREIGN KEY ("id_actividad") REFERENCES "Actividad" ("id_actividad") DEFERRABLE INITIALLY IMMEDIATE;

-- Misma regla que ya tiene Turno (migración 002): si hay profesor, tiene que
-- estar habilitado para esa actividad. Se valida acá también porque si el
-- horario guarda un profesor no habilitado, el error recién aparecería al
-- generar los turnos — lejos, en un proceso automático, y no en el formulario
-- donde alguien lo eligió mal.
ALTER TABLE "Horario_Actividad" DROP CONSTRAINT IF EXISTS fk_horario_profesor_habilitado;
ALTER TABLE "Horario_Actividad" ADD CONSTRAINT fk_horario_profesor_habilitado
  FOREIGN KEY ("id_profesor", "id_actividad")
  REFERENCES "Profesor_Actividad" ("id_profesor", "id_actividad")
  DEFERRABLE INITIALLY IMMEDIATE;

COMMENT ON TABLE "Horario_Actividad" IS
  'Horario semanal de cada actividad. El backend genera los Turno de las proximas semanas a partir de aca, en vez de que alguien los cargue uno por uno.';


-- -----------------------------------------------------------------------------
-- De qué horario nació cada turno.
--
-- NULL = cargado a mano. La generación automática nunca toca esos: alguien
-- los creó por algo (una clase extra, un recuperatorio) y no le corresponde
-- a un proceso decidir que sobran.
-- -----------------------------------------------------------------------------
ALTER TABLE "Turno"
  ADD COLUMN IF NOT EXISTS "id_horario_actividad" int;

ALTER TABLE "Turno" DROP CONSTRAINT IF EXISTS "Turno_id_horario_actividad_fkey";
ALTER TABLE "Turno" ADD FOREIGN KEY ("id_horario_actividad")
  REFERENCES "Horario_Actividad" ("id_horario_actividad")
  DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX IF NOT EXISTS turno_horario_idx
  ON "Turno" ("id_horario_actividad")
  WHERE "id_horario_actividad" IS NOT NULL;

COMMENT ON COLUMN "Turno"."id_horario_actividad" IS
  'Horario semanal que genero este turno. NULL = cargado a mano; la generacion automatica no lo toca.';

-- =============================================================================
-- REVERTIR:
--   DROP INDEX IF EXISTS turno_horario_idx;
--   ALTER TABLE "Turno" DROP COLUMN IF EXISTS "id_horario_actividad";
--   DROP TABLE IF EXISTS "Horario_Actividad";
--
--   El valor 'EN_ESPERA' del enum NO se puede quitar: Postgres no soporta
--   sacar valores de un enum. Habria que recrear el tipo y todas las columnas
--   que lo usan. Si molesta, alcanza con no usarlo — ninguna consulta lo
--   requiere.
-- =============================================================================
