-- =============================================================================
-- 008 — Congelamiento de membresia
-- =============================================================================
-- Pausar la cuota por un viaje o una lesion, sin perder los dias pagados.
--
-- POR QUE UNA TABLA Y NO DOS COLUMNAS EN Membresia:
--
-- Es el mismo criterio que ya siguen Baja y Asignacion_Rutina. Un socio
-- congela mas de una vez a lo largo del tiempo, y cada congelamiento tiene su
-- propio motivo y sus propias fechas. Con dos columnas en Membresia, el
-- segundo congelamiento pisaria al primero y el historial se perderia — que
-- es justamente el dato que hace falta para poder aplicar un tope anual.
--
-- COMO INTERACTUA CON fecha_vencimiento:
--
-- Congelar EXTIENDE el vencimiento por la cantidad de dias congelados. El
-- socio pago un mes y tiene que recibir un mes de gimnasio; si se va tres
-- semanas de viaje, esas tres semanas no se le descuentan.
--
-- La extension se aplica al REANUDAR y no al congelar, y esa diferencia
-- importa: al congelar todavia no se sabe cuantos dias van a ser en serio.
-- Alguien que pide 30 dias y vuelve a los 10 tiene que recuperar 10, no 30.
-- Si se extendiera por adelantado habria que descontar la diferencia despues,
-- y ese es el tipo de correccion que sale mal.
--
-- Un congelamiento que llega a su fecha_fin sin que nadie lo reanude se
-- cierra solo: el backend lo detecta al leerlo (misma idea que el estado
-- derivado de las reservas — ver turnos.py). No hace falta un proceso.
--
-- Es idempotente.
--
-- Aplicar:  SQL Editor de Neon, o  psql ... -f 008_congelamiento_de_membresia.sql
-- Revertir: ver el bloque del final (comentado).
-- =============================================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_congelamiento') THEN
    CREATE TYPE "estado_congelamiento" AS ENUM (
      'ACTIVO',      -- en curso
      'FINALIZADO',  -- se reanudo, o se llego a la fecha de fin
      'CANCELADO'    -- se dio marcha atras antes de que empezara
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "Congelamiento" (
  "id_congelamiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_membresia" int NOT NULL,
  "fecha_inicio" date NOT NULL,
  -- Hasta cuando lo pidio. Es un TOPE, no una promesa: se puede reanudar
  -- antes, y en ese caso solo se extiende por los dias realmente congelados.
  "fecha_fin" date NOT NULL,
  -- Cuando se reanudo de verdad. NULL mientras sigue congelada.
  "fecha_reanudacion" date,
  -- Los dias que efectivamente se sumaron al vencimiento. Se escribe al
  -- reanudar. Se guarda calculado y no se deriva de las fechas porque es el
  -- numero que ya se aplico a la membresia: si manana cambia la forma de
  -- contarlos, el historico tiene que seguir explicando el vencimiento real.
  "dias_aplicados" int,
  "motivo" varchar(200),
  "estado" estado_congelamiento NOT NULL DEFAULT 'ACTIVO',
  "fecha_solicitud" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT chk_congelamiento_rango CHECK ("fecha_fin" >= "fecha_inicio")
);

ALTER TABLE "Congelamiento" DROP CONSTRAINT IF EXISTS "Congelamiento_id_socio_fkey";
ALTER TABLE "Congelamiento" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Congelamiento" DROP CONSTRAINT IF EXISTS "Congelamiento_id_membresia_fkey";
ALTER TABLE "Congelamiento" ADD FOREIGN KEY ("id_membresia") REFERENCES "Membresia" ("id_membresia") DEFERRABLE INITIALLY IMMEDIATE;

-- Un solo congelamiento ACTIVO por socio a la vez. Dos superpuestos harian
-- imposible saber cuantos dias sumarle al vencimiento sin contarlos dos veces.
CREATE UNIQUE INDEX IF NOT EXISTS congelamiento_uno_activo_uidx
  ON "Congelamiento" ("id_socio")
  WHERE "estado" = 'ACTIVO';

CREATE INDEX IF NOT EXISTS congelamiento_socio_idx
  ON "Congelamiento" ("id_socio", "fecha_inicio");

COMMENT ON TABLE "Congelamiento" IS
  'Pausas de membresia. Al reanudar se extiende Membresia.fecha_vencimiento por los dias realmente congelados, no por los pedidos.';

-- =============================================================================
-- REVERTIR:
--   DROP TABLE IF EXISTS "Congelamiento";
--   DROP TYPE IF EXISTS "estado_congelamiento";
-- =============================================================================
