CREATE TYPE "metodo_pago" AS ENUM (
  'EFECTIVO',
  'DEBITO',
  'CREDITO',
  'TRANSFERENCIA',
  'BILLETERA_VIRTUAL'
);

CREATE TYPE "estado_membresia" AS ENUM (
  'ACTIVA',
  'VENCIDA',
  'SUSPENDIDA',
  'CANCELADA'
);

CREATE TYPE "estado_pago" AS ENUM (
  'CONFIRMADO',
  'PENDIENTE',
  'CANCELADO',
  'REEMBOLSADO'
);

CREATE TYPE "estado_deuda" AS ENUM (
  'PENDIENTE',
  'PAGADA',
  'CONDONADA'
);

CREATE TYPE "estado_turno" AS ENUM (
  'HABILITADO',
  'CANCELADO'
);

CREATE TYPE "estado_reserva" AS ENUM (
  'RESERVADA',
  -- Anotado pero sin lugar todavia. NO ocupa cupo: todo conteo de ocupacion
  -- tiene que filtrar por estado = 'RESERVADA'. Si alguien cancela, el
  -- backend promueve al EN_ESPERA mas antiguo de ese turno. Ver migracion 005.
  'EN_ESPERA',
  'CANCELADA_SOCIO',
  'CANCELADA_GIMNASIO'
);

CREATE TYPE "estado_asignacion" AS ENUM (
  'ACTIVA',
  'FINALIZADA',
  'CANCELADA'
);

CREATE TYPE "tipo_baja" AS ENUM (
  'VOLUNTARIA',
  'MORA',
  'ADMINISTRATIVA'
);

CREATE TYPE "tipo_telefono" AS ENUM (
  'CELULAR',
  'FIJO'
);

CREATE TYPE "tipo_limite" AS ENUM (
  'POR_SEMANA',
  'POR_MES'
);

CREATE TYPE "estado_inscripcion" AS ENUM (
  'ACTIVA',
  'VENCIDA',
  'CANCELADA'
);

CREATE TYPE "metodo_registro" AS ENUM (
  'RFID',
  'MANUAL'
);

CREATE TABLE "Sede" (
  "id_sede" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_dueno" int NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "calle" varchar(100),
  "numero_calle" varchar(10),
  "localidad" varchar(80),
  "telefono" varchar(30),
  "capacidad_maxima" int,
  "hora_apertura" time,
  "hora_cierre" time,
  "abierto_24hs" boolean DEFAULT true,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Persona" (
  "id_persona" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dni" varchar(20) UNIQUE NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "sexo" varchar(20),
  "email" varchar(150) UNIQUE,
  "calle" varchar(100),
  "numero_calle" varchar(10),
  "localidad" varchar(80),
  "fecha_nacimiento" date,
  "emergencia_nombre" varchar(150),
  "emergencia_telefono" varchar(30),
  "emergencia_parentesco" varchar(50),
  "fecha_alta" timestamp DEFAULT (now()),
  "activo" boolean DEFAULT true
);

CREATE TABLE "Telefono" (
  "id_telefono" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int NOT NULL,
  "numero" varchar(30) NOT NULL,
  "tipo" tipo_telefono DEFAULT 'CELULAR',
  "principal" boolean DEFAULT false
);

CREATE TABLE "Usuario" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int UNIQUE NOT NULL,
  "username" varchar(50) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  -- Fuerza el cambio de contraseña en el próximo ingreso. Arranca en true a
  -- propósito: toda cuenta nace con una clave temporal que alguien más eligió
  -- (el seeder para el dueño, el personal para un socio o empleado), así que
  -- lo correcto por defecto es exigir que la cambien. Cuando está en true, el
  -- login NO emite token — ver migrations/001.
  "debe_cambiar_password" boolean NOT NULL DEFAULT true,
  "ultimo_acceso" timestamp,
  "intentos_fallidos" int DEFAULT 0,
  "bloqueado" boolean DEFAULT false,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Dueno" (
  "id_dueno" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int UNIQUE NOT NULL,
  "porcentaje_participacion" decimal(5,2)
);

CREATE TABLE "Empleado" (
  "id_empleado" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int UNIQUE NOT NULL,
  "id_sede" int NOT NULL,
  "legajo" varchar(20) UNIQUE,
  "fecha_ingreso" date NOT NULL,
  "fecha_egreso" date,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Entrenador" (
  "id_entrenador" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empleado" int UNIQUE NOT NULL,
  "titulo" varchar(100),
  "especialidad" varchar(100),
  "matricula" varchar(50)
);

CREATE TABLE "Nutricionista" (
  "id_nutricionista" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empleado" int UNIQUE NOT NULL,
  "titulo" varchar(100),
  "matricula" varchar(50)
);

CREATE TABLE "Recepcionista" (
  "id_recepcionista" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empleado" int UNIQUE NOT NULL,
  "turno_laboral" varchar(20)
);

CREATE TABLE "Profesor" (
  "id_profesor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empleado" int UNIQUE NOT NULL,
  "titulo" varchar(100),
  "especialidad" varchar(100)
);

CREATE TABLE "Socio" (
  "id_socio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int UNIQUE NOT NULL,
  "id_sede" int NOT NULL,
  "numero_socio" varchar(20) UNIQUE,
  "codigo_rfid" varchar(50) UNIQUE,
  "fecha_alta" date NOT NULL,
  "objetivo" varchar(150),
  "observaciones" text,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Baja" (
  "id_baja" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "fecha_baja" date NOT NULL,
  "tipo" tipo_baja,
  "motivo" varchar(250)
);

CREATE TABLE "Tipo_Membresia" (
  "id_tipo_membresia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "descripcion" text,
  "duracion_dias" int NOT NULL,
  "precio_actual" decimal(10,2) NOT NULL,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Promocion" (
  "id_promocion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_dueno" int NOT NULL,
  "id_sede" int,
  "nombre" varchar(100) NOT NULL,
  "descripcion" text,
  "porcentaje_descuento" decimal(5,2),
  "monto_fijo_descuento" decimal(10,2),
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date NOT NULL,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Membresia" (
  "id_membresia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_tipo_membresia" int NOT NULL,
  "id_promocion" int,
  "precio_pactado" decimal(10,2) NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_vencimiento" date,
  "estado" estado_membresia DEFAULT 'ACTIVA'
);

CREATE TABLE "Pago" (
  "id_pago" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_membresia" int,
  "id_inscripcion" int,
  "id_sede" int,
  "metodo" metodo_pago NOT NULL,
  "monto" decimal(10,2) NOT NULL,
  "fecha_pago" timestamp NOT NULL DEFAULT (now()),
  "periodo_desde" date,
  "periodo_hasta" date,
  "es_adelanto" boolean DEFAULT false,
  "estado" estado_pago DEFAULT 'CONFIRMADO',
  "fecha_cancelacion" timestamp,
  "numero_comprobante" varchar(50) UNIQUE
);

CREATE TABLE "Deuda" (
  "id_deuda" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_membresia" int,
  "monto" decimal(10,2) NOT NULL,
  "fecha_generacion" date NOT NULL,
  "fecha_vencimiento" date,
  "estado" estado_deuda DEFAULT 'PENDIENTE',
  "generada_automaticamente" boolean DEFAULT true,
  "id_pago_cancelatorio" int,
  "observaciones" varchar(250)
);

CREATE TABLE "Registro_Salud" (
  "id_registro_salud" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "fecha" date NOT NULL,
  "peso" decimal(5,2),
  "altura" decimal(3,2),
  "grasa_corporal" decimal(4,2),
  "masa_muscular" decimal(5,2),
  "observaciones" text
);

CREATE TABLE "Patologia" (
  "id_patologia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "descripcion" text
);

CREATE TABLE "Socio_Patologia" (
  "id_socio" int,
  "id_patologia" int,
  "fecha_diagnostico" date,
  "observaciones" text,
  PRIMARY KEY ("id_socio", "id_patologia")
);

CREATE TABLE "Ejercicio" (
  "id_ejercicio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "grupo_muscular" varchar(50) NOT NULL,
  "descripcion" text,
  "url_video" varchar(255),
  "requiere_maquina" boolean DEFAULT false
);

CREATE TABLE "Rutina" (
  "id_rutina" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_entrenador" int NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "objetivo" varchar(100),
  "nivel" varchar(20),
  "dias_por_semana" int,
  "fecha_creacion" date DEFAULT (now()),
  "activo" boolean DEFAULT true
);

CREATE TABLE "Rutina_Ejercicio" (
  "id_rutina_ejercicio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_rutina" int NOT NULL,
  "id_ejercicio" int NOT NULL,
  "dia" int NOT NULL,
  "orden" int NOT NULL,
  "series" int,
  "repeticiones" varchar(20),
  "peso_sugerido" decimal(6,2),
  "descanso_segundos" int,
  "observaciones" varchar(200)
);

CREATE TABLE "Asignacion_Rutina" (
  "id_asignacion_rutina" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_rutina" int NOT NULL,
  "id_entrenador" int,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date,
  "estado" estado_asignacion DEFAULT 'ACTIVA'
);

-- Historiza Socio<->Entrenador ("a cargo"). Reemplaza a Socio.id_entrenador_a_cargo
-- (columna de valor único: no podía representar más de un entrenador activo a
-- la vez ni conservar a los anteriores). Mismo patrón que Asignacion_Rutina /
-- Asignacion_Dieta: PK subrogada + fecha_inicio/fecha_fin/estado.
-- A DIFERENCIA de esas dos: acá SÍ está permitido tener más de una fila con
-- estado = 'ACTIVA' para el mismo socio en simultáneo (decisión de negocio:
-- un socio puede tener, por ejemplo, un entrenador de musculación y otro de
-- funcional al mismo tiempo). "Entrenador(es) a cargo actuales" =
-- SELECT ... WHERE id_socio = X AND estado = 'ACTIVA'.
CREATE TABLE "Asignacion_Entrenador" (
  "id_asignacion_entrenador" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_entrenador" int NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date,
  "estado" estado_asignacion DEFAULT 'ACTIVA'
);

CREATE TABLE "Dieta" (
  "id_dieta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_nutricionista" int NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "objetivo" varchar(100),
  "calorias_diarias" int,
  "descripcion" text,
  "fecha_creacion" date DEFAULT (now()),
  "activo" boolean DEFAULT true
);

CREATE TABLE "Comida" (
  "id_comida" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_dieta" int NOT NULL,
  "dia" int,
  "momento" varchar(30),
  "descripcion" text NOT NULL,
  "calorias" int
);

CREATE TABLE "Asignacion_Dieta" (
  "id_asignacion_dieta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_dieta" int NOT NULL,
  "id_nutricionista" int,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date,
  "estado" estado_asignacion DEFAULT 'ACTIVA',
  "observaciones" text
);

CREATE TABLE "Actividad" (
  "id_actividad" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(80) UNIQUE NOT NULL,
  "descripcion" text,
  "cupo_default" int NOT NULL,
  "precio_clase_suelta" decimal(10,2) NOT NULL,
  "horas_anticipacion_cancelacion" int NOT NULL DEFAULT 0,
  -- Minutos despues de la hora del turno en que todavia se acepta la llegada.
  -- Pasado ese margen la reserva cuenta como ausente y la tarjeta no valida
  -- ese turno. Vive por actividad y no como constante porque no es la misma
  -- para una clase de Yoga que para la sala de musculacion. Ver migracion 004.
  "minutos_tolerancia" int NOT NULL DEFAULT 15,
  "activo" boolean DEFAULT true,
  CONSTRAINT chk_actividad_tolerancia
    CHECK ("minutos_tolerancia" >= 0 AND "minutos_tolerancia" <= 180)
);

CREATE TABLE "Plan_Actividad" (
  "id_plan_actividad" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_actividad" int NOT NULL,
  "nombre" varchar(80) NOT NULL,
  "tipo_limite" tipo_limite NOT NULL,
  "cantidad" int NOT NULL,
  "precio" decimal(10,2) NOT NULL,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Inscripcion_Actividad" (
  "id_inscripcion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_plan_actividad" int NOT NULL,
  "id_membresia" int NOT NULL,
  "precio_pactado" decimal(10,2) NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_vencimiento" date NOT NULL,
  "clases_restantes" int,
  "estado" estado_inscripcion DEFAULT 'ACTIVA'
);

CREATE TABLE "Profesor_Actividad" (
  "id_profesor" int NOT NULL,
  "id_actividad" int NOT NULL,
  PRIMARY KEY ("id_profesor", "id_actividad")
);

CREATE TABLE "Horario_Actividad" (
  "id_horario_actividad" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_sede" int NOT NULL,
  "id_actividad" int NOT NULL,
  -- ISO: 1 = lunes ... 7 = domingo. ISO y no el DOW nativo de Postgres
  -- (0 = domingo) porque aca la semana empieza el lunes, igual que en el
  -- calendario que ve la gente; y porque EXTRACT(ISODOW FROM fecha) devuelve
  -- exactamente esto, asi la generacion de turnos compara sin convertir nada.
  "dia_semana" int NOT NULL,
  "hora" time NOT NULL,
  "cupo" int NOT NULL,
  "id_profesor" int,
  -- Excluyente con id_profesor, igual que en Turno. Ambos NULL = sala abierta.
  "id_entrenador_a_cargo" int,
  -- vigente_hasta NULL = indefinido. Permite decir "Yoga pasa a las 20:00 a
  -- partir del 1 de marzo" sin borrar el horario viejo ni perder los turnos
  -- ya generados con el anterior.
  "vigente_desde" date NOT NULL,
  "vigente_hasta" date,
  "activo" boolean DEFAULT true,
  CONSTRAINT chk_horario_dia_semana CHECK ("dia_semana" BETWEEN 1 AND 7),
  CONSTRAINT chk_horario_cupo CHECK ("cupo" > 0),
  CONSTRAINT chk_horario_vigencia
    CHECK ("vigente_hasta" IS NULL OR "vigente_hasta" >= "vigente_desde"),
  CONSTRAINT chk_horario_un_solo_staff
    CHECK (NOT ("id_entrenador_a_cargo" IS NOT NULL AND "id_profesor" IS NOT NULL))
);

CREATE TABLE "Turno" (
  "id_turno" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_sede" int NOT NULL,
  "id_actividad" int NOT NULL,
  "fecha" date NOT NULL,
  "hora" time NOT NULL,
  "cupo_maximo" int NOT NULL,
  "estado" estado_turno DEFAULT 'HABILITADO',
  "id_entrenador_a_cargo" int,
  "id_profesor" int,
  -- De que horario semanal nacio este turno. NULL = cargado a mano, y la
  -- generacion automatica no lo toca: alguien lo creo por algo (una clase
  -- extra, un recuperatorio) y no le corresponde a un proceso decidir que sobra.
  "id_horario_actividad" int,
  "motivo_cancelacion" varchar(200),
  "observaciones" varchar(200)
);

CREATE TABLE "Reserva" (
  "id_reserva" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_turno" int NOT NULL,
  "id_socio" int NOT NULL,
  "id_inscripcion" int,
  "es_clase_suelta" boolean DEFAULT false,
  "id_pago" int,
  "fecha_reserva" timestamp DEFAULT (now()),
  "estado" estado_reserva DEFAULT 'RESERVADA',
  "fecha_cancelacion" timestamp
);

CREATE TABLE "Asistencia" (
  "id_asistencia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_sede" int NOT NULL,
  "id_reserva" int,
  "fecha_hora_ingreso" timestamp NOT NULL,
  "fecha_hora_egreso" timestamp,
  "metodo_registro" metodo_registro NOT NULL DEFAULT 'MANUAL',
  "id_registrado_por" int
);

CREATE TABLE "Consulta_Cruzada" (
  "id_consulta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empleado" int NOT NULL,
  "id_rutina" int,
  "id_dieta" int,
  "fecha_consulta" timestamp DEFAULT (now())
);

CREATE UNIQUE INDEX ON "Membresia" ("id_socio", "fecha_inicio");

CREATE INDEX ON "Membresia" ("estado", "fecha_vencimiento");

CREATE INDEX ON "Pago" ("id_socio", "fecha_pago");

CREATE INDEX ON "Pago" ("id_sede", "fecha_pago");

CREATE INDEX ON "Deuda" ("id_socio", "estado");

CREATE UNIQUE INDEX ON "Registro_Salud" ("id_socio", "fecha");

CREATE INDEX ON "Ejercicio" ("grupo_muscular");

CREATE UNIQUE INDEX ON "Rutina_Ejercicio" ("id_rutina", "dia", "orden");

CREATE UNIQUE INDEX ON "Asignacion_Rutina" ("id_socio", "id_rutina", "fecha_inicio");

-- Nombradas explícitamente (no auto-generadas) a propósito: así la migración
-- 003 puede recrearlas de forma idempotente (CREATE ... IF NOT EXISTS por
-- nombre) sin importar si la base nació de este schema.sql o fue migrada.
CREATE UNIQUE INDEX asignacion_entrenador_socio_entrenador_fecha_uidx
  ON "Asignacion_Entrenador" ("id_socio", "id_entrenador", "fecha_inicio");

CREATE INDEX asignacion_entrenador_socio_estado_idx
  ON "Asignacion_Entrenador" ("id_socio", "estado");

CREATE INDEX ON "Asignacion_Rutina" ("id_socio", "estado");

CREATE INDEX ON "Comida" ("id_dieta", "dia");

CREATE INDEX ON "Asignacion_Dieta" ("id_socio", "estado");

-- Una sola rutina y una sola dieta VIGENTES por socio. El WHERE es lo que
-- hace que funcione: sin el, un socio no podria tener mas de una asignacion
-- en toda su vida. Lo que se prohibe son dos a la VEZ, no dos a lo largo del
-- tiempo — el historial es el motivo por el que estas tablas existen.
--
-- Asignacion_Entrenador NO lleva este indice a proposito: ahi varios a la vez
-- es lo correcto (uno de musculacion y otro de funcional). Ver migracion 009.
--
-- OJO: un indice unico PARCIAL no puede ser DEFERRABLE, asi que se evalua al
-- terminar cada sentencia. El endpoint que reasigna tiene que hacer flush del
-- UPDATE que finaliza la anterior ANTES de insertar la nueva.
CREATE UNIQUE INDEX asignacion_rutina_una_activa_uidx
  ON "Asignacion_Rutina" ("id_socio") WHERE "estado" = 'ACTIVA';

CREATE UNIQUE INDEX asignacion_dieta_una_activa_uidx
  ON "Asignacion_Dieta" ("id_socio") WHERE "estado" = 'ACTIVA';

-- El que le faltaba a Dieta, para que las tres asignaciones se comporten
-- igual en lo que si comparten: no repetir el mismo item el mismo dia.
CREATE UNIQUE INDEX asignacion_dieta_socio_dieta_fecha_uidx
  ON "Asignacion_Dieta" ("id_socio", "id_dieta", "fecha_inicio");

CREATE INDEX ON "Inscripcion_Actividad" ("id_socio", "estado");

-- Reemplaza el unique viejo ("un Turno = un día"): ahora un mismo día/sede
-- puede tener varios turnos, uno por actividad+hora.
CREATE UNIQUE INDEX ON "Turno" ("id_sede", "id_actividad", "fecha", "hora");

CREATE INDEX ON "Turno" ("id_actividad", "fecha");

-- Para el panel de proximos turnos del recepcionista: siempre pide los turnos
-- habilitados de hoy ordenados por hora, y se refresca solo cada pocos
-- segundos. Es la consulta mas repetida del sistema.
CREATE INDEX turno_fecha_hora_estado_idx ON "Turno" ("fecha", "hora", "estado");

CREATE UNIQUE INDEX ON "Reserva" ("id_turno", "id_socio");

CREATE INDEX ON "Reserva" ("id_turno", "estado");

CREATE INDEX ON "Asistencia" ("id_socio", "fecha_hora_ingreso");

CREATE INDEX ON "Asistencia" ("id_sede", "fecha_hora_ingreso");

-- El panel del recepcionista resuelve, para cada reserva que muestra, si ya
-- hay una entrada registrada — es asi como se deriva "asistio" sin guardarlo
-- como estado. Sin este indice es un scan de Asistencia por cada fila.
CREATE INDEX asistencia_reserva_idx ON "Asistencia" ("id_reserva")
  WHERE "id_reserva" IS NOT NULL;

CREATE INDEX ON "Consulta_Cruzada" ("id_empleado", "fecha_consulta");

COMMENT ON TABLE "Sede" IS 'Raíz organizativa. Un gimnasio de una sola sucursal tiene una fila.';

COMMENT ON TABLE "Persona" IS 'SUPERTIPO. Atributos comunes viven acá, no repetidos por rol.
1FN: nombre/apellido separados, dirección descompuesta.
Contacto de emergencia como columnas (monovaluado, cumple 1FN).
';

COMMENT ON TABLE "Telefono" IS '1FN: una persona puede tener varios teléfonos -> tabla propia.';

COMMENT ON TABLE "Usuario" IS 'DFD 1.1.2 login. El rol se DERIVA de en qué subtipo aparece la persona.';

COMMENT ON TABLE "Empleado" IS '3FN: el dueño se obtiene vía Sede, no se repite acá.';

COMMENT ON TABLE "Baja" IS 'DFD 1.1.3 / 6.3.2. Un socio puede reinscribirse -> es un hecho con fecha.';

COMMENT ON TABLE "Tipo_Membresia" IS '3FN: saca la dependencia transitiva Tipo -> Precio de Membresia.';

COMMENT ON TABLE "Promocion" IS 'DFD 2.2. id_sede NULL = aplica a todas las sedes.';

COMMENT ON TABLE "Membresia" IS '1:N con Socio -> historial de renovaciones.
precio_pactado (histórico) != Tipo_Membresia.precio_actual (vigente): no viola 3FN.
';

COMMENT ON TABLE "Pago" IS 'DFD 2.1. Un pago nunca se borra: estado = CANCELADO.';

COMMENT ON TABLE "Deuda" IS 'DFD 2.3. Se genera automáticamente al vencer una membresía impaga (job diario).';

COMMENT ON TABLE "Registro_Salud" IS 'HISTORICO 1:N. unique (id_socio, fecha) impide dos pesos el mismo día,
pero conserva la progresión. Peso actual = SELECT ... ORDER BY fecha DESC LIMIT 1.
';

COMMENT ON TABLE "Patologia" IS '3FN: catálogo.';

COMMENT ON TABLE "Socio_Patologia" IS '1FN: rompe el varchar multivaluado. 2FN: atributos dependen de la clave completa.';

COMMENT ON TABLE "Ejercicio" IS '3FN: grupo_muscular depende del ejercicio, no de la rutina.';

COMMENT ON TABLE "Rutina" IS 'DFD 3.1.';

COMMENT ON TABLE "Rutina_Ejercicio" IS '1FN: una rutina tiene muchos ejercicios -> tabla intermedia.';

COMMENT ON TABLE "Asignacion_Rutina" IS 'PK subrogada: permite historial y varias rutinas por socio.';

COMMENT ON TABLE "Asignacion_Entrenador" IS 'Historiza Socio<->Entrenador ("a cargo"). Mismo patrón que Asignacion_Rutina/Asignacion_Dieta, pero permitiendo varias filas ACTIVA por socio a la vez (varios entrenadores simultáneos).';

COMMENT ON TABLE "Dieta" IS 'DFD 4.1.';

COMMENT ON TABLE "Comida" IS '1FN: una dieta tiene varias comidas -> tabla propia.';

COMMENT ON TABLE "Asignacion_Dieta" IS 'Almacén "Dietas asignadas" del DFD 4.2. N:M.';

COMMENT ON TABLE "Profesor" IS 'Subtipo de Empleado, DISTINTO de Entrenador: Entrenador da rutinas de
musculación, Profesor dicta el resto de las actividades (yoga, boxeo,
masajes). Una persona puede tener las dos filas si cumple los dos roles.
';

COMMENT ON TABLE "Actividad" IS 'Catálogo de lo que se puede reservar en un Turno. Musculación es una
fila más acá, no un caso aparte: permite tratar todo bajo el mismo
modelo de Turno/Reserva/Inscripción en vez de duplicar la lógica.
';

COMMENT ON TABLE "Plan_Actividad" IS 'Formatos de pago de una Actividad (ej. "2x semana" o "12 clases/mes").
tipo_limite = POR_SEMANA -> cantidad = veces por semana.
tipo_limite = POR_MES -> cantidad = clases totales del mes.
';

COMMENT ON TABLE "Inscripcion_Actividad" IS 'Lo que un socio compró de un Plan_Actividad. id_membresia ata la
inscripción a la membresía que la cubre: no puede vencer después que
la membresía (se valida al comprar, no se corrige después).
clases_restantes sólo se usa si el plan es POR_MES; en POR_SEMANA el
consumo se cuenta dinámicamente sobre Reserva, no se guarda contador.
';

COMMENT ON TABLE "Profesor_Actividad" IS 'N:M: qué actividades puede dictar cada profesor.';

COMMENT ON TABLE "Turno" IS 'Un turno es una actividad con horario, en una fecha y sede (musculación
incluida: también es una fila de Actividad). id_entrenador_a_cargo es
para musculación/rutinas; id_profesor para el resto. hora es SOLO de
llegada, no hay hora de fin (DFD original: acceso libre 24hs).
';

COMMENT ON TABLE "Reserva" IS 'DFD 5.2. unique impide reservar dos veces el mismo día.';

COMMENT ON TABLE "Asistencia" IS '1:N con Reserva: el socio puede entrar y salir varias veces por día.';

COMMENT ON TABLE "Consulta_Cruzada" IS 'Un nutricionista consulta la rutina de un socio (para ajustar dieta al gasto)
o un entrenador consulta la dieta. El consultor apunta a Empleado (supertipo).
Requiere CHECK en el SQL (DBML no lo soporta):
  CHECK ( (id_rutina IS NOT NULL) <> (id_dieta IS NOT NULL) )
';

ALTER TABLE "Sede" ADD FOREIGN KEY ("id_dueno") REFERENCES "Dueno" ("id_dueno") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Telefono" ADD FOREIGN KEY ("id_persona") REFERENCES "Persona" ("id_persona") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Usuario" ADD FOREIGN KEY ("id_persona") REFERENCES "Persona" ("id_persona") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Dueno" ADD FOREIGN KEY ("id_persona") REFERENCES "Persona" ("id_persona") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Empleado" ADD FOREIGN KEY ("id_persona") REFERENCES "Persona" ("id_persona") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Empleado" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Entrenador" ADD FOREIGN KEY ("id_empleado") REFERENCES "Empleado" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Nutricionista" ADD FOREIGN KEY ("id_empleado") REFERENCES "Empleado" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Recepcionista" ADD FOREIGN KEY ("id_empleado") REFERENCES "Empleado" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Socio" ADD FOREIGN KEY ("id_persona") REFERENCES "Persona" ("id_persona") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Socio" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Baja" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Promocion" ADD FOREIGN KEY ("id_dueno") REFERENCES "Dueno" ("id_dueno") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Promocion" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Membresia" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Membresia" ADD FOREIGN KEY ("id_tipo_membresia") REFERENCES "Tipo_Membresia" ("id_tipo_membresia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Membresia" ADD FOREIGN KEY ("id_promocion") REFERENCES "Promocion" ("id_promocion") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Pago" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Pago" ADD FOREIGN KEY ("id_membresia") REFERENCES "Membresia" ("id_membresia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Pago" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Deuda" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Deuda" ADD FOREIGN KEY ("id_membresia") REFERENCES "Membresia" ("id_membresia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Deuda" ADD FOREIGN KEY ("id_pago_cancelatorio") REFERENCES "Pago" ("id_pago") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Registro_Salud" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Socio_Patologia" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Socio_Patologia" ADD FOREIGN KEY ("id_patologia") REFERENCES "Patologia" ("id_patologia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Rutina" ADD FOREIGN KEY ("id_entrenador") REFERENCES "Entrenador" ("id_entrenador") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Rutina_Ejercicio" ADD FOREIGN KEY ("id_rutina") REFERENCES "Rutina" ("id_rutina") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Rutina_Ejercicio" ADD FOREIGN KEY ("id_ejercicio") REFERENCES "Ejercicio" ("id_ejercicio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Rutina" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Rutina" ADD FOREIGN KEY ("id_rutina") REFERENCES "Rutina" ("id_rutina") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Rutina" ADD FOREIGN KEY ("id_entrenador") REFERENCES "Entrenador" ("id_entrenador") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Entrenador" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Entrenador" ADD FOREIGN KEY ("id_entrenador") REFERENCES "Entrenador" ("id_entrenador") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Dieta" ADD FOREIGN KEY ("id_nutricionista") REFERENCES "Nutricionista" ("id_nutricionista") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Comida" ADD FOREIGN KEY ("id_dieta") REFERENCES "Dieta" ("id_dieta") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Dieta" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Dieta" ADD FOREIGN KEY ("id_dieta") REFERENCES "Dieta" ("id_dieta") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Dieta" ADD FOREIGN KEY ("id_nutricionista") REFERENCES "Nutricionista" ("id_nutricionista") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Turno" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Turno" ADD FOREIGN KEY ("id_entrenador_a_cargo") REFERENCES "Entrenador" ("id_entrenador") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Reserva" ADD FOREIGN KEY ("id_turno") REFERENCES "Turno" ("id_turno") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Reserva" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asistencia" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asistencia" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asistencia" ADD FOREIGN KEY ("id_reserva") REFERENCES "Reserva" ("id_reserva") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Consulta_Cruzada" ADD FOREIGN KEY ("id_empleado") REFERENCES "Empleado" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Consulta_Cruzada" ADD FOREIGN KEY ("id_rutina") REFERENCES "Rutina" ("id_rutina") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Consulta_Cruzada" ADD FOREIGN KEY ("id_dieta") REFERENCES "Dieta" ("id_dieta") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Profesor" ADD FOREIGN KEY ("id_empleado") REFERENCES "Empleado" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Plan_Actividad" ADD FOREIGN KEY ("id_actividad") REFERENCES "Actividad" ("id_actividad") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Inscripcion_Actividad" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Inscripcion_Actividad" ADD FOREIGN KEY ("id_plan_actividad") REFERENCES "Plan_Actividad" ("id_plan_actividad") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Inscripcion_Actividad" ADD FOREIGN KEY ("id_membresia") REFERENCES "Membresia" ("id_membresia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Profesor_Actividad" ADD FOREIGN KEY ("id_profesor") REFERENCES "Profesor" ("id_profesor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Profesor_Actividad" ADD FOREIGN KEY ("id_actividad") REFERENCES "Actividad" ("id_actividad") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Turno" ADD FOREIGN KEY ("id_actividad") REFERENCES "Actividad" ("id_actividad") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Turno" ADD FOREIGN KEY ("id_profesor") REFERENCES "Profesor" ("id_profesor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Reserva" ADD FOREIGN KEY ("id_inscripcion") REFERENCES "Inscripcion_Actividad" ("id_inscripcion") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Reserva" ADD FOREIGN KEY ("id_pago") REFERENCES "Pago" ("id_pago") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asistencia" ADD FOREIGN KEY ("id_registrado_por") REFERENCES "Usuario" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Pago" ADD FOREIGN KEY ("id_inscripcion") REFERENCES "Inscripcion_Actividad" ("id_inscripcion") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Consulta_Cruzada"
ADD CONSTRAINT chk_una_referencia
CHECK ( ("id_rutina" IS NOT NULL) <> ("id_dieta" IS NOT NULL) );
-- ============================================================================
-- BLINDAJE DE INTEGRIDAD (agregado a schema.sql)
-- Estas reglas no se podían expresar como CHECK simple porque cruzan tablas
-- y/o evalúan la AUSENCIA de filas. Para bases que se crearon ANTES de este
-- bloque, el equivalente idempotente está en migrations/002_blindaje_integridad.sql
-- ============================================================================

-- ---------------------------------------------------------------------------
-- (A) EMPLEADO SIN SUBTIPO ("empleado colgado")
-- Todo Empleado debe existir en al menos uno de sus subtipos (Entrenador,
-- Nutricionista, Recepcionista, Profesor). Es una restricción de TOTALIDAD
-- de la jerarquía supertipo/subtipo, con subtipos SOLAPADOS (una persona
-- puede ser Entrenador y Profesor a la vez), así que no sirve un discriminador
-- único. Se resuelve con un CONSTRAINT TRIGGER DEFERIDO que valida al COMMIT,
-- para que el alta en dos pasos (Empleado -> subtipo) dentro de una tx pase.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_empleado_debe_tener_subtipo()
RETURNS trigger AS $$
DECLARE
  v_id_empleado int;
  v_existe      boolean;
  v_tiene       boolean;
BEGIN
  -- Empleado en riesgo de quedar colgado:
  --   INSERT en Empleado          -> NEW (el recién creado)
  --   DELETE/UPDATE en un subtipo -> OLD (el que perdió el rol)
  IF TG_TABLE_NAME = 'Empleado' THEN
    v_id_empleado := NEW.id_empleado;
  ELSE
    v_id_empleado := OLD.id_empleado;
  END IF;

  -- Si el empleado ya no existe (se borró en la misma tx), no exigimos nada.
  SELECT EXISTS(SELECT 1 FROM "Empleado" WHERE id_empleado = v_id_empleado)
    INTO v_existe;
  IF NOT v_existe THEN
    RETURN NULL;
  END IF;

  SELECT
       EXISTS(SELECT 1 FROM "Entrenador"    WHERE id_empleado = v_id_empleado)
    OR EXISTS(SELECT 1 FROM "Nutricionista" WHERE id_empleado = v_id_empleado)
    OR EXISTS(SELECT 1 FROM "Recepcionista" WHERE id_empleado = v_id_empleado)
    OR EXISTS(SELECT 1 FROM "Profesor"      WHERE id_empleado = v_id_empleado)
    INTO v_tiene;

  IF NOT v_tiene THEN
    RAISE EXCEPTION
      'Empleado % no tiene subtipo. Todo empleado debe ser al menos uno de: Entrenador, Nutricionista, Recepcionista o Profesor.',
      v_id_empleado
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_empleado_completo ON "Empleado";
CREATE CONSTRAINT TRIGGER trg_empleado_completo
  AFTER INSERT ON "Empleado"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION trg_empleado_debe_tener_subtipo();

DROP TRIGGER IF EXISTS trg_entrenador_no_deja_colgado ON "Entrenador";
CREATE CONSTRAINT TRIGGER trg_entrenador_no_deja_colgado
  AFTER DELETE OR UPDATE OF id_empleado ON "Entrenador"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION trg_empleado_debe_tener_subtipo();

DROP TRIGGER IF EXISTS trg_nutri_no_deja_colgado ON "Nutricionista";
CREATE CONSTRAINT TRIGGER trg_nutri_no_deja_colgado
  AFTER DELETE OR UPDATE OF id_empleado ON "Nutricionista"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION trg_empleado_debe_tener_subtipo();

DROP TRIGGER IF EXISTS trg_recep_no_deja_colgado ON "Recepcionista";
CREATE CONSTRAINT TRIGGER trg_recep_no_deja_colgado
  AFTER DELETE OR UPDATE OF id_empleado ON "Recepcionista"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION trg_empleado_debe_tener_subtipo();

DROP TRIGGER IF EXISTS trg_profesor_no_deja_colgado ON "Profesor";
CREATE CONSTRAINT TRIGGER trg_profesor_no_deja_colgado
  AFTER DELETE OR UPDATE OF id_empleado ON "Profesor"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION trg_empleado_debe_tener_subtipo();

-- ---------------------------------------------------------------------------
-- (B) CONFUSIÓN DE STAFF EN TURNO
-- (b1) Un turno NUNCA lleva entrenador Y profesor a la vez. Ambos-NULL SÍ se
--      permite: un turno de musculación de acceso libre puede no tener staff.
-- (b2) Si lleva profesor, ese profesor tiene que estar habilitado para dictar
--      esa actividad. Se enforcea con FK COMPUESTA contra Profesor_Actividad:
--      declarativo y sin hardcodear "Musculación". Como una FK con columnas
--      NULL no se chequea (MATCH SIMPLE), los turnos sin profesor quedan
--      exentos automáticamente.
-- ---------------------------------------------------------------------------
ALTER TABLE "Turno" DROP CONSTRAINT IF EXISTS chk_turno_un_solo_staff;
ALTER TABLE "Turno" ADD CONSTRAINT chk_turno_un_solo_staff
  CHECK (NOT ("id_entrenador_a_cargo" IS NOT NULL AND "id_profesor" IS NOT NULL));

ALTER TABLE "Turno" DROP CONSTRAINT IF EXISTS fk_turno_profesor_habilitado;
ALTER TABLE "Turno" ADD CONSTRAINT fk_turno_profesor_habilitado
  FOREIGN KEY ("id_profesor", "id_actividad")
  REFERENCES "Profesor_Actividad" ("id_profesor", "id_actividad")
  DEFERRABLE INITIALLY IMMEDIATE;

COMMENT ON CONSTRAINT chk_turno_un_solo_staff ON "Turno" IS
  'Un turno no puede tener entrenador y profesor a la vez (ambos-NULL permitido).';
COMMENT ON CONSTRAINT fk_turno_profesor_habilitado ON "Turno" IS
  'El profesor asignado a un turno debe estar habilitado para esa actividad (Profesor_Actividad).';

-- -----------------------------------------------------------------------------
-- Horario_Actividad — claves, indices y su version de la regla del profesor
-- -----------------------------------------------------------------------------
ALTER TABLE "Horario_Actividad" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Horario_Actividad" ADD FOREIGN KEY ("id_actividad") REFERENCES "Actividad" ("id_actividad") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Horario_Actividad" ADD FOREIGN KEY ("id_entrenador_a_cargo") REFERENCES "Entrenador" ("id_entrenador") DEFERRABLE INITIALLY IMMEDIATE;

-- Misma regla que Turno: si hay profesor, tiene que estar habilitado para esa
-- actividad. Se valida tambien aca porque si el horario guarda un profesor no
-- habilitado, el error recien aparaceria al generar los turnos — lejos, en un
-- proceso automatico, y no en el formulario donde alguien lo eligio mal.
ALTER TABLE "Horario_Actividad" ADD CONSTRAINT fk_horario_profesor_habilitado
  FOREIGN KEY ("id_profesor", "id_actividad")
  REFERENCES "Profesor_Actividad" ("id_profesor", "id_actividad")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Turno" ADD FOREIGN KEY ("id_horario_actividad")
  REFERENCES "Horario_Actividad" ("id_horario_actividad") DEFERRABLE INITIALLY IMMEDIATE;

-- No puede haber dos horarios activos para la misma actividad, mismo dia y
-- misma hora: generarian el mismo turno dos veces.
CREATE UNIQUE INDEX horario_actividad_slot_uidx
  ON "Horario_Actividad" ("id_sede", "id_actividad", "dia_semana", "hora")
  WHERE "activo";

CREATE INDEX horario_actividad_activo_idx ON "Horario_Actividad" ("activo", "dia_semana");

CREATE INDEX turno_horario_idx ON "Turno" ("id_horario_actividad")
  WHERE "id_horario_actividad" IS NOT NULL;
