CREATE TYPE "metodo_pago" AS ENUM (
  'EFECTIVO',
  'DEBITO',
  'CREDITO',
  'TRANSFERENCIA',
  'BILLETERA_VIRTUAL'
);

CREATE TYPE "estado_membresia" AS ENUM (
  'ACTIVA',
  'VENCIDA',
  'SUSPENDIDA',
  'CANCELADA'
);

CREATE TYPE "estado_pago" AS ENUM (
  'CONFIRMADO',
  'PENDIENTE',
  'CANCELADO',
  'REEMBOLSADO'
);

CREATE TYPE "estado_deuda" AS ENUM (
  'PENDIENTE',
  'PAGADA',
  'CONDONADA'
);

CREATE TYPE "estado_turno" AS ENUM (
  'HABILITADO',
  'CANCELADO'
);

CREATE TYPE "estado_reserva" AS ENUM (
  'RESERVADA',
  'CANCELADA_SOCIO',
  'CANCELADA_GIMNASIO'
);

CREATE TYPE "estado_asignacion" AS ENUM (
  'ACTIVA',
  'FINALIZADA',
  'CANCELADA'
);

CREATE TYPE "tipo_baja" AS ENUM (
  'VOLUNTARIA',
  'MORA',
  'ADMINISTRATIVA'
);

CREATE TYPE "tipo_telefono" AS ENUM (
  'CELULAR',
  'FIJO'
);

CREATE TABLE "Sede" (
  "id_sede" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_dueno" int NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "calle" varchar(100),
  "numero_calle" varchar(10),
  "localidad" varchar(80),
  "telefono" varchar(30),
  "capacidad_maxima" int,
  "hora_apertura" time,
  "hora_cierre" time,
  "abierto_24hs" boolean DEFAULT true,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Persona" (
  "id_persona" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dni" varchar(20) UNIQUE NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "sexo" varchar(20),
  "email" varchar(150) UNIQUE,
  "calle" varchar(100),
  "numero_calle" varchar(10),
  "localidad" varchar(80),
  "fecha_nacimiento" date,
  "emergencia_nombre" varchar(150),
  "emergencia_telefono" varchar(30),
  "emergencia_parentesco" varchar(50),
  "fecha_alta" timestamp DEFAULT (now()),
  "activo" boolean DEFAULT true
);

CREATE TABLE "Telefono" (
  "id_telefono" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int NOT NULL,
  "numero" varchar(30) NOT NULL,
  "tipo" tipo_telefono DEFAULT 'CELULAR',
  "principal" boolean DEFAULT false
);

CREATE TABLE "Usuario" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int UNIQUE NOT NULL,
  "username" varchar(50) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "ultimo_acceso" timestamp,
  "intentos_fallidos" int DEFAULT 0,
  "bloqueado" boolean DEFAULT false,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Dueno" (
  "id_dueno" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int UNIQUE NOT NULL,
  "porcentaje_participacion" decimal(5,2)
);

CREATE TABLE "Empleado" (
  "id_empleado" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int UNIQUE NOT NULL,
  "id_sede" int NOT NULL,
  "legajo" varchar(20) UNIQUE,
  "fecha_ingreso" date NOT NULL,
  "fecha_egreso" date,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Entrenador" (
  "id_entrenador" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empleado" int UNIQUE NOT NULL,
  "titulo" varchar(100),
  "especialidad" varchar(100),
  "matricula" varchar(50)
);

CREATE TABLE "Nutricionista" (
  "id_nutricionista" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empleado" int UNIQUE NOT NULL,
  "titulo" varchar(100),
  "matricula" varchar(50)
);

CREATE TABLE "Recepcionista" (
  "id_recepcionista" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empleado" int UNIQUE NOT NULL,
  "turno_laboral" varchar(20)
);

CREATE TABLE "Socio" (
  "id_socio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int UNIQUE NOT NULL,
  "id_sede" int NOT NULL,
  "id_entrenador_a_cargo" int,
  "numero_socio" varchar(20) UNIQUE,
  "fecha_alta" date NOT NULL,
  "objetivo" varchar(150),
  "observaciones" text,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Baja" (
  "id_baja" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "fecha_baja" date NOT NULL,
  "tipo" tipo_baja,
  "motivo" varchar(250)
);

CREATE TABLE "Tipo_Membresia" (
  "id_tipo_membresia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "descripcion" text,
  "duracion_dias" int NOT NULL,
  "precio_actual" decimal(10,2) NOT NULL,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Promocion" (
  "id_promocion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_dueno" int NOT NULL,
  "id_sede" int,
  "nombre" varchar(100) NOT NULL,
  "descripcion" text,
  "porcentaje_descuento" decimal(5,2),
  "monto_fijo_descuento" decimal(10,2),
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date NOT NULL,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Membresia" (
  "id_membresia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_tipo_membresia" int NOT NULL,
  "id_promocion" int,
  "precio_pactado" decimal(10,2) NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_vencimiento" date NOT NULL,
  "estado" estado_membresia DEFAULT 'ACTIVA'
);

CREATE TABLE "Pago" (
  "id_pago" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_membresia" int,
  "id_sede" int,
  "metodo" metodo_pago NOT NULL,
  "monto" decimal(10,2) NOT NULL,
  "fecha_pago" timestamp NOT NULL DEFAULT (now()),
  "periodo_desde" date,
  "periodo_hasta" date,
  "es_adelanto" boolean DEFAULT false,
  "estado" estado_pago DEFAULT 'CONFIRMADO',
  "fecha_cancelacion" timestamp,
  "numero_comprobante" varchar(50) UNIQUE
);

CREATE TABLE "Deuda" (
  "id_deuda" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_membresia" int,
  "monto" decimal(10,2) NOT NULL,
  "fecha_generacion" date NOT NULL,
  "fecha_vencimiento" date,
  "estado" estado_deuda DEFAULT 'PENDIENTE',
  "generada_automaticamente" boolean DEFAULT true,
  "id_pago_cancelatorio" int,
  "observaciones" varchar(250)
);

CREATE TABLE "Registro_Salud" (
  "id_registro_salud" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "fecha" date NOT NULL,
  "peso" decimal(5,2),
  "altura" decimal(3,2),
  "grasa_corporal" decimal(4,2),
  "masa_muscular" decimal(5,2),
  "observaciones" text
);

CREATE TABLE "Patologia" (
  "id_patologia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "descripcion" text
);

CREATE TABLE "Socio_Patologia" (
  "id_socio" int,
  "id_patologia" int,
  "fecha_diagnostico" date,
  "observaciones" text,
  PRIMARY KEY ("id_socio", "id_patologia")
);

CREATE TABLE "Ejercicio" (
  "id_ejercicio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "grupo_muscular" varchar(50) NOT NULL,
  "descripcion" text,
  "url_video" varchar(255),
  "requiere_maquina" boolean DEFAULT false
);

CREATE TABLE "Rutina" (
  "id_rutina" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_entrenador" int NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "objetivo" varchar(100),
  "nivel" varchar(20),
  "dias_por_semana" int,
  "fecha_creacion" date DEFAULT (now()),
  "activo" boolean DEFAULT true
);

CREATE TABLE "Rutina_Ejercicio" (
  "id_rutina_ejercicio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_rutina" int NOT NULL,
  "id_ejercicio" int NOT NULL,
  "dia" int NOT NULL,
  "orden" int NOT NULL,
  "series" int,
  "repeticiones" varchar(20),
  "peso_sugerido" decimal(6,2),
  "descanso_segundos" int,
  "observaciones" varchar(200)
);

CREATE TABLE "Asignacion_Rutina" (
  "id_asignacion_rutina" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_rutina" int NOT NULL,
  "id_entrenador" int,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date,
  "estado" estado_asignacion DEFAULT 'ACTIVA'
);

CREATE TABLE "Dieta" (
  "id_dieta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_nutricionista" int NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "objetivo" varchar(100),
  "calorias_diarias" int,
  "descripcion" text,
  "fecha_creacion" date DEFAULT (now()),
  "activo" boolean DEFAULT true
);

CREATE TABLE "Comida" (
  "id_comida" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_dieta" int NOT NULL,
  "dia" int,
  "momento" varchar(30),
  "descripcion" text NOT NULL,
  "calorias" int
);

CREATE TABLE "Asignacion_Dieta" (
  "id_asignacion_dieta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_dieta" int NOT NULL,
  "id_nutricionista" int,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date,
  "estado" estado_asignacion DEFAULT 'ACTIVA',
  "observaciones" text
);

CREATE TABLE "Turno" (
  "id_turno" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_sede" int NOT NULL,
  "fecha" date NOT NULL,
  "cupo_maximo" int NOT NULL,
  "estado" estado_turno DEFAULT 'HABILITADO',
  "id_entrenador_a_cargo" int,
  "motivo_cancelacion" varchar(200),
  "observaciones" varchar(200)
);

CREATE TABLE "Reserva" (
  "id_reserva" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_turno" int NOT NULL,
  "id_socio" int NOT NULL,
  "fecha_reserva" timestamp DEFAULT (now()),
  "estado" estado_reserva DEFAULT 'RESERVADA',
  "fecha_cancelacion" timestamp
);

CREATE TABLE "Asistencia" (
  "id_asistencia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_socio" int NOT NULL,
  "id_sede" int NOT NULL,
  "id_reserva" int,
  "fecha_hora_ingreso" timestamp NOT NULL,
  "fecha_hora_egreso" timestamp
);

CREATE TABLE "Consulta_Cruzada" (
  "id_consulta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empleado" int NOT NULL,
  "id_rutina" int,
  "id_dieta" int,
  "fecha_consulta" timestamp DEFAULT (now())
);

CREATE UNIQUE INDEX ON "Membresia" ("id_socio", "fecha_inicio");

CREATE INDEX ON "Membresia" ("estado", "fecha_vencimiento");

CREATE INDEX ON "Pago" ("id_socio", "fecha_pago");

CREATE INDEX ON "Pago" ("id_sede", "fecha_pago");

CREATE INDEX ON "Deuda" ("id_socio", "estado");

CREATE UNIQUE INDEX ON "Registro_Salud" ("id_socio", "fecha");

CREATE INDEX ON "Ejercicio" ("grupo_muscular");

CREATE UNIQUE INDEX ON "Rutina_Ejercicio" ("id_rutina", "dia", "orden");

CREATE UNIQUE INDEX ON "Asignacion_Rutina" ("id_socio", "id_rutina", "fecha_inicio");

CREATE INDEX ON "Asignacion_Rutina" ("id_socio", "estado");

CREATE INDEX ON "Comida" ("id_dieta", "dia");

CREATE INDEX ON "Asignacion_Dieta" ("id_socio", "estado");

CREATE UNIQUE INDEX ON "Turno" ("id_sede", "fecha");

CREATE UNIQUE INDEX ON "Reserva" ("id_turno", "id_socio");

CREATE INDEX ON "Reserva" ("id_turno", "estado");

CREATE INDEX ON "Asistencia" ("id_socio", "fecha_hora_ingreso");

CREATE INDEX ON "Asistencia" ("id_sede", "fecha_hora_ingreso");

CREATE INDEX ON "Consulta_Cruzada" ("id_empleado", "fecha_consulta");

COMMENT ON TABLE "Sede" IS 'Raíz organizativa. Un gimnasio de una sola sucursal tiene una fila.';

COMMENT ON TABLE "Persona" IS 'SUPERTIPO. Atributos comunes viven acá, no repetidos por rol.
1FN: nombre/apellido separados, dirección descompuesta.
Contacto de emergencia como columnas (monovaluado, cumple 1FN).
';

COMMENT ON TABLE "Telefono" IS '1FN: una persona puede tener varios teléfonos -> tabla propia.';

COMMENT ON TABLE "Usuario" IS 'DFD 1.1.2 login. El rol se DERIVA de en qué subtipo aparece la persona.';

COMMENT ON TABLE "Empleado" IS '3FN: el dueño se obtiene vía Sede, no se repite acá.';

COMMENT ON TABLE "Baja" IS 'DFD 1.1.3 / 6.3.2. Un socio puede reinscribirse -> es un hecho con fecha.';

COMMENT ON TABLE "Tipo_Membresia" IS '3FN: saca la dependencia transitiva Tipo -> Precio de Membresia.';

COMMENT ON TABLE "Promocion" IS 'DFD 2.2. id_sede NULL = aplica a todas las sedes.';

COMMENT ON TABLE "Membresia" IS '1:N con Socio -> historial de renovaciones.
precio_pactado (histórico) != Tipo_Membresia.precio_actual (vigente): no viola 3FN.
';

COMMENT ON TABLE "Pago" IS 'DFD 2.1. Un pago nunca se borra: estado = CANCELADO.';

COMMENT ON TABLE "Deuda" IS 'DFD 2.3. Se genera automáticamente al vencer una membresía impaga (job diario).';

COMMENT ON TABLE "Registro_Salud" IS 'HISTORICO 1:N. unique (id_socio, fecha) impide dos pesos el mismo día,
pero conserva la progresión. Peso actual = SELECT ... ORDER BY fecha DESC LIMIT 1.
';

COMMENT ON TABLE "Patologia" IS '3FN: catálogo.';

COMMENT ON TABLE "Socio_Patologia" IS '1FN: rompe el varchar multivaluado. 2FN: atributos dependen de la clave completa.';

COMMENT ON TABLE "Ejercicio" IS '3FN: grupo_muscular depende del ejercicio, no de la rutina.';

COMMENT ON TABLE "Rutina" IS 'DFD 3.1.';

COMMENT ON TABLE "Rutina_Ejercicio" IS '1FN: una rutina tiene muchos ejercicios -> tabla intermedia.';

COMMENT ON TABLE "Asignacion_Rutina" IS 'PK subrogada: permite historial y varias rutinas por socio.';

COMMENT ON TABLE "Dieta" IS 'DFD 4.1.';

COMMENT ON TABLE "Comida" IS '1FN: una dieta tiene varias comidas -> tabla propia.';

COMMENT ON TABLE "Asignacion_Dieta" IS 'Almacén "Dietas asignadas" del DFD 4.2. N:M.';

COMMENT ON TABLE "Turno" IS 'Un Turno = un DÍA habilitado con cupo en una sede (acceso libre 24hs).
PENDIENTE: si se agregan actividades con horario fijo (boxeo, pilates,
yoga, masajes), agregar tabla Actividad + hora_inicio/hora_fin y ampliar
el unique. Decisión de alcance sin resolver todavía.
';

COMMENT ON TABLE "Reserva" IS 'DFD 5.2. unique impide reservar dos veces el mismo día.';

COMMENT ON TABLE "Asistencia" IS '1:N con Reserva: el socio puede entrar y salir varias veces por día.';

COMMENT ON TABLE "Consulta_Cruzada" IS 'Un nutricionista consulta la rutina de un socio (para ajustar dieta al gasto)
o un entrenador consulta la dieta. El consultor apunta a Empleado (supertipo).
Requiere CHECK en el SQL (DBML no lo soporta):
  CHECK ( (id_rutina IS NOT NULL) <> (id_dieta IS NOT NULL) )
';

ALTER TABLE "Sede" ADD FOREIGN KEY ("id_dueno") REFERENCES "Dueno" ("id_dueno") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Telefono" ADD FOREIGN KEY ("id_persona") REFERENCES "Persona" ("id_persona") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Usuario" ADD FOREIGN KEY ("id_persona") REFERENCES "Persona" ("id_persona") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Dueno" ADD FOREIGN KEY ("id_persona") REFERENCES "Persona" ("id_persona") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Empleado" ADD FOREIGN KEY ("id_persona") REFERENCES "Persona" ("id_persona") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Empleado" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Entrenador" ADD FOREIGN KEY ("id_empleado") REFERENCES "Empleado" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Nutricionista" ADD FOREIGN KEY ("id_empleado") REFERENCES "Empleado" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Recepcionista" ADD FOREIGN KEY ("id_empleado") REFERENCES "Empleado" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Socio" ADD FOREIGN KEY ("id_persona") REFERENCES "Persona" ("id_persona") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Socio" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Socio" ADD FOREIGN KEY ("id_entrenador_a_cargo") REFERENCES "Entrenador" ("id_entrenador") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Baja" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Promocion" ADD FOREIGN KEY ("id_dueno") REFERENCES "Dueno" ("id_dueno") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Promocion" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Membresia" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Membresia" ADD FOREIGN KEY ("id_tipo_membresia") REFERENCES "Tipo_Membresia" ("id_tipo_membresia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Membresia" ADD FOREIGN KEY ("id_promocion") REFERENCES "Promocion" ("id_promocion") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Pago" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Pago" ADD FOREIGN KEY ("id_membresia") REFERENCES "Membresia" ("id_membresia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Pago" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Deuda" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Deuda" ADD FOREIGN KEY ("id_membresia") REFERENCES "Membresia" ("id_membresia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Deuda" ADD FOREIGN KEY ("id_pago_cancelatorio") REFERENCES "Pago" ("id_pago") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Registro_Salud" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Socio_Patologia" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Socio_Patologia" ADD FOREIGN KEY ("id_patologia") REFERENCES "Patologia" ("id_patologia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Rutina" ADD FOREIGN KEY ("id_entrenador") REFERENCES "Entrenador" ("id_entrenador") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Rutina_Ejercicio" ADD FOREIGN KEY ("id_rutina") REFERENCES "Rutina" ("id_rutina") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Rutina_Ejercicio" ADD FOREIGN KEY ("id_ejercicio") REFERENCES "Ejercicio" ("id_ejercicio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Rutina" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Rutina" ADD FOREIGN KEY ("id_rutina") REFERENCES "Rutina" ("id_rutina") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Rutina" ADD FOREIGN KEY ("id_entrenador") REFERENCES "Entrenador" ("id_entrenador") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Dieta" ADD FOREIGN KEY ("id_nutricionista") REFERENCES "Nutricionista" ("id_nutricionista") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Comida" ADD FOREIGN KEY ("id_dieta") REFERENCES "Dieta" ("id_dieta") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Dieta" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Dieta" ADD FOREIGN KEY ("id_dieta") REFERENCES "Dieta" ("id_dieta") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asignacion_Dieta" ADD FOREIGN KEY ("id_nutricionista") REFERENCES "Nutricionista" ("id_nutricionista") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Turno" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Turno" ADD FOREIGN KEY ("id_entrenador_a_cargo") REFERENCES "Entrenador" ("id_entrenador") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Reserva" ADD FOREIGN KEY ("id_turno") REFERENCES "Turno" ("id_turno") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Reserva" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asistencia" ADD FOREIGN KEY ("id_socio") REFERENCES "Socio" ("id_socio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asistencia" ADD FOREIGN KEY ("id_sede") REFERENCES "Sede" ("id_sede") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Asistencia" ADD FOREIGN KEY ("id_reserva") REFERENCES "Reserva" ("id_reserva") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Consulta_Cruzada" ADD FOREIGN KEY ("id_empleado") REFERENCES "Empleado" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Consulta_Cruzada" ADD FOREIGN KEY ("id_rutina") REFERENCES "Rutina" ("id_rutina") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Consulta_Cruzada" ADD FOREIGN KEY ("id_dieta") REFERENCES "Dieta" ("id_dieta") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Consulta_Cruzada"
ADD CONSTRAINT chk_una_referencia
CHECK ( ("id_rutina" IS NOT NULL) <> ("id_dieta" IS NOT NULL) );