-- =============================================================================
-- OlimpOS — schema.sql
-- =============================================================================
-- FORGE · Esquema completo y definitivo · PostgreSQL 14+
--
-- 41 tablas · 13 enums · 66 claves foráneas (64 simples + 2 compuestas)
--
-- Este archivo crea una base DESDE CERO. No correrlo sobre una base con datos.
--
-- Estilo: identidades declaradas en línea con GENERATED BY DEFAULT AS IDENTITY
-- (equivale al ALTER TABLE separado que generaba pg_dump, pero se lee de un
-- vistazo). Las claves foráneas van agrupadas al final para que el orden de
-- creación de las tablas no importe.
--
-- -----------------------------------------------------------------------------
-- ORDEN DE EJECUCIÓN
-- -----------------------------------------------------------------------------
--   1. Este archivo (schema.sql)
--   2. seed.sql
--
-- -----------------------------------------------------------------------------
-- LOS CUATRO CRITERIOS QUE EXPLICAN CADA DECISIÓN DE ACÁ
-- -----------------------------------------------------------------------------
--   1. NO GUARDAR LO QUE SE PUEDE DERIVAR. Un dato calculado que además se
--      guarda crea una segunda fuente de verdad que se desincroniza. Por eso no
--      hay estados ASISTIO/AUSENTE (se deducen de si hay fila en Asistencia), ni
--      peso actual en Socio (sale de Registro_Salud ORDER BY fecha DESC LIMIT 1).
--
--   2. LAS DECISIONES DE NEGOCIO VAN COMO DATOS, NO COMO CONSTANTES. Si el dueño
--      tiene que llamar a un programador para cambiar algo suyo, el dato está mal
--      ubicado. Por eso la tolerancia y las horas de anticipación son columnas de
--      Actividad, y los precios son filas de Plan_Actividad.
--
--   3. MENOS TABLAS ES MEJOR, PERO NO MENOS DE LAS NECESARIAS. Una tabla se
--      justifica si hay atributos exclusivos de un subconjunto, si el hecho es
--      múltiple, si el pasado importa, si es N:M, si es catálogo o si es evento.
--      Si nada de eso aplica, alcanza con un enum o una columna.
--
--   4. LAS RESTRICCIONES DE BASE SE RESERVAN PARA EL DAÑO IRREVERSIBLE. Lo que se
--      corrige cambiando un ID vive en el backend.
--
-- -----------------------------------------------------------------------------
-- NADA SE BORRA
-- -----------------------------------------------------------------------------
-- Ninguna clave foránea declara ON DELETE, así que rige el NO ACTION implícito
-- del estándar. Es deliberado y no un olvido: los pagos se marcan CANCELADO o
-- REEMBOLSADO, las bajas, los turnos y las reservas también se marcan. Nada se
-- destruye. El NO ACTION es la defensa de esa política.
--
-- Todas las FK son DEFERRABLE para permitir altas en varios pasos dentro de una
-- misma transacción (por ejemplo Empleado y después su subtipo).
-- =============================================================================


-- =============================================================================
-- 1. TIPOS ENUMERADOS
-- =============================================================================
-- Un enum cierra el dominio de valores posibles de una columna: nada fuera de la
-- lista puede entrar. Todas las columnas que los usan son NOT NULL, porque un
-- NULL en un enum de estados sería precisamente un valor fuera del dominio.

CREATE TYPE estado_asignacion    AS ENUM ('ACTIVA', 'FINALIZADA', 'CANCELADA');
CREATE TYPE estado_congelamiento AS ENUM ('ACTIVO', 'FINALIZADO', 'CANCELADO');
CREATE TYPE estado_inscripcion   AS ENUM ('ACTIVA', 'VENCIDA', 'CANCELADA');
CREATE TYPE estado_membresia     AS ENUM ('ACTIVA', 'VENCIDA', 'SUSPENDIDA', 'CANCELADA');
CREATE TYPE estado_pago          AS ENUM ('CONFIRMADO', 'PENDIENTE', 'CANCELADO', 'REEMBOLSADO');
CREATE TYPE estado_reserva       AS ENUM ('RESERVADA', 'EN_ESPERA', 'CANCELADA_SOCIO', 'CANCELADA_GIMNASIO');
CREATE TYPE estado_turno         AS ENUM ('HABILITADO', 'CANCELADO');
CREATE TYPE metodo_pago          AS ENUM ('EFECTIVO', 'DEBITO', 'CREDITO', 'TRANSFERENCIA', 'BILLETERA_VIRTUAL');
CREATE TYPE metodo_registro      AS ENUM ('RFID', 'MANUAL');
CREATE TYPE origen_congelamiento AS ENUM ('SOCIO', 'GIMNASIO');
CREATE TYPE tipo_baja            AS ENUM ('VOLUNTARIA', 'MORA', 'ADMINISTRATIVA');
CREATE TYPE tipo_limite          AS ENUM ('POR_SEMANA', 'POR_MES', 'CLASE_SUELTA');
CREATE TYPE tipo_telefono        AS ENUM ('CELULAR', 'FIJO');


-- =============================================================================
-- 2. PERSONAS Y ROLES
-- =============================================================================

CREATE TABLE "Persona" (
    id_persona        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni               character varying(20) NOT NULL UNIQUE,
    apellido          character varying(100) NOT NULL,
    nombre            character varying(100) NOT NULL,
    sexo              character varying(20),
    email             character varying(150) UNIQUE,
    calle             character varying(100),
    numero_calle      character varying(10),
    localidad         character varying(80),
    fecha_nacimiento  date,
    fecha_alta        timestamp without time zone DEFAULT now(),
    activo            boolean DEFAULT true
);

COMMENT ON TABLE "Persona" IS
'SUPERTIPO. Los atributos comunes viven aca y no se repiten por rol.
1FN: nombre y apellido separados, direccion descompuesta en calle/numero/localidad.
Los telefonos van en Telefono y los contactos de emergencia en Contacto_Emergencia:
ambos son multivaluados y por eso tienen tabla propia.
PENDIENTE: sexo es varchar libre. Deberia ser enum o catalogo, como los otros 13.';


CREATE TABLE "Telefono" (
    id_telefono  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona   integer NOT NULL,
    numero       character varying(30) NOT NULL,
    tipo         tipo_telefono DEFAULT 'CELULAR',
    principal    boolean DEFAULT false
);

COMMENT ON TABLE "Telefono" IS
'1FN: una persona puede tener varios telefonos, asi que no pueden ser columnas.';


CREATE TABLE "Contacto_Emergencia" (
    id_contacto_emergencia integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona             integer NOT NULL,
    nombre                 character varying(150) NOT NULL,
    telefono               character varying(30) NOT NULL,
    parentesco             character varying(50),
    principal              boolean DEFAULT false
);

COMMENT ON TABLE "Contacto_Emergencia" IS
'Multivaluado, por eso tabla propia y no columnas de Persona.
Asimetria deliberada: el telefono va inline aca, mientras que los de Persona
viven en Telefono. Se justifica porque el contacto de emergencia NO es una
Persona del sistema: es un dato de contacto externo, no un actor.';


CREATE TABLE "Usuario" (
    id_usuario             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona             integer NOT NULL UNIQUE,
    username               character varying(50) NOT NULL UNIQUE,
    password_hash          character varying(255) NOT NULL,
    debe_cambiar_password  boolean NOT NULL DEFAULT true,
    ultimo_acceso          timestamp without time zone,
    intentos_fallidos      integer DEFAULT 0,
    bloqueado              boolean DEFAULT false,
    activo                 boolean DEFAULT true
);

COMMENT ON TABLE "Usuario" IS
'DFD 1.1.2 login. El rol se DERIVA de en que subtipo aparece la persona: no hay
columna de rol porque seria una segunda fuente de verdad.
ABIERTO: una Persona puede ser Socio Y Empleado a la vez (los UNIQUE son
independientes entre si). Si eso ocurre, la derivacion del rol queda ambigua.';


CREATE TABLE "Dueno" (
    id_dueno                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona               integer NOT NULL UNIQUE,
    porcentaje_participacion numeric(5,2)
);

COMMENT ON TABLE "Dueno" IS
'PENDIENTE: falta CHECK de rango 0-100 en porcentaje_participacion.';


CREATE TABLE "Sede" (
    id_sede           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_dueno          integer NOT NULL,
    nombre            character varying(100) NOT NULL,
    calle             character varying(100),
    numero_calle      character varying(10),
    localidad         character varying(80),
    telefono          character varying(30),
    capacidad_maxima  integer,
    hora_apertura     time without time zone,
    hora_cierre       time without time zone,
    abierto_24hs      boolean DEFAULT true,
    activo            boolean DEFAULT true,

    -- Parece redundante porque id_sede ya es PK, pero sin esta clave candidata
    -- no se puede declarar la FK compuesta que Promocion usa para garantizar
    -- que su dueno coincida con el de su sede.
    CONSTRAINT sede_id_dueno_uk UNIQUE (id_sede, id_dueno)
);

COMMENT ON TABLE "Sede" IS
'Raiz organizativa. Un gimnasio de una sola sucursal tiene una fila. El modelo
soporta varias sedes, pero eso es prevision, no un requerimiento actual.';


CREATE TABLE "Empleado" (
    id_empleado     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona      integer NOT NULL UNIQUE,
    id_sede         integer NOT NULL,
    legajo          character varying(20) UNIQUE,
    fecha_ingreso   date NOT NULL,
    fecha_egreso    date,
    activo          boolean DEFAULT true
);

COMMENT ON TABLE "Empleado" IS
'3FN: el dueno se obtiene via Sede y no se repite aca.
TRIGGER trg_empleado_completo: todo Empleado debe ser al menos uno de sus cuatro
subtipos. Es un CONSTRAINT TRIGGER DIFERIDO que valida al COMMIT y no al INSERT,
para que el alta en dos pasos (Empleado -> subtipo) funcione en una transaccion.';


CREATE TABLE "Entrenador" (
    id_entrenador  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado    integer NOT NULL UNIQUE,
    titulo         character varying(100),
    especialidad   character varying(100),
    matricula      character varying(50)
);

COMMENT ON TABLE "Entrenador" IS
'Subtipo de Empleado. Arma rutinas de musculacion y hace seguimiento personalizado.
DISTINTO de Profesor: son subtipos SOLAPADOS, una misma persona puede tener las
dos filas si cumple los dos roles.';


CREATE TABLE "Profesor" (
    id_profesor   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado   integer NOT NULL UNIQUE,
    titulo        character varying(100),
    especialidad  character varying(100)
);

COMMENT ON TABLE "Profesor" IS
'Subtipo de Empleado. Dicta las clases grupales con horario fijo (yoga, boxeo).';


CREATE TABLE "Nutricionista" (
    id_nutricionista  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado       integer NOT NULL UNIQUE,
    titulo            character varying(100),
    matricula         character varying(50)
);


CREATE TABLE "Franja_Laboral" (
    id_franja_laboral  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre             character varying(40) NOT NULL UNIQUE,
    hora_desde         time without time zone,
    hora_hasta         time without time zone,
    activo             boolean DEFAULT true
);


CREATE TABLE "Recepcionista" (
    id_recepcionista   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado        integer NOT NULL UNIQUE,
    id_franja_laboral  integer
);

COMMENT ON TABLE "Recepcionista" IS
'Subtipo de Empleado. No produce nada propio: solo opera el sistema.
Es el UNICO subtipo con franja laboral. Los demas derivan su horario de Turno y
Horario_Actividad, asi que no la necesitan.';


-- =============================================================================
-- 3. SOCIO — el centro del modelo. 13 tablas lo referencian directamente.
-- =============================================================================

CREATE TABLE "Socio" (
    id_socio       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona     integer NOT NULL UNIQUE,
    id_sede        integer NOT NULL,
    numero_socio   character varying(20) UNIQUE,
    codigo_rfid    character varying(50) UNIQUE,
    fecha_alta     date NOT NULL,
    objetivo       character varying(150),
    observaciones  text,
    activo         boolean DEFAULT true
);

COMMENT ON TABLE "Socio" IS
'Subtipo de Persona y centro del modelo.
No guarda peso actual: sale de Registro_Salud con ORDER BY fecha DESC LIMIT 1.
ABIERTO — asimetria alta/baja: existe la tabla Baja como hecho con fecha, pero no
hay un hecho Alta simetrico: fecha_alta es una sola columna. Si el socio se va y
vuelve, la fecha de reinscripcion no tiene donde vivir.';


CREATE TABLE "Patologia" (
    id_patologia  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        character varying(100) NOT NULL UNIQUE,
    descripcion   text
);

COMMENT ON TABLE "Patologia" IS
'3FN: catalogo. El nombre depende de la patologia, no del socio que la tiene.';


CREATE TABLE "Socio_Patologia" (
    id_socio            integer NOT NULL,
    id_patologia        integer NOT NULL,
    fecha_diagnostico   date,
    observaciones       text,

    PRIMARY KEY (id_socio, id_patologia)
);

COMMENT ON TABLE "Socio_Patologia" IS
'1FN: rompe lo que seria un varchar multivaluado de patologias.
2FN: fecha_diagnostico y observaciones dependen de la clave COMPLETA (socio +
patologia), no de una sola de sus partes.';


CREATE TABLE "Baja" (
    id_baja      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio     integer NOT NULL,
    fecha_baja   date NOT NULL,
    tipo         tipo_baja,
    motivo       character varying(250),
    pendiente    boolean NOT NULL DEFAULT false
);

COMMENT ON TABLE "Baja" IS
'DFD 1.1.3 / 6.3.2. Un socio puede reinscribirse, asi que la baja es un HECHO con
fecha y no un booleano de Socio. Nada se borra: las bajas se marcan.
PENDIENTE: tipo admite NULL, pero toda baja tiene necesariamente un tipo.';

COMMENT ON COLUMN "Baja".pendiente IS
'true = baja PROGRAMADA: el socio tenia un periodo pago en curso y la baja corre
desde fecha_baja (el dia siguiente al vencimiento); hasta entonces sigue activo. Se
aplica sola al llegar la fecha (backend/bajas.py) y pasa a false. Mientras este
pendiente se puede anular: la fila se borra, porque una baja que no ocurrio no es
historial. Existe para no quitarle al socio los dias que ya pago.';


CREATE TABLE "Registro_Salud" (
    id_registro_salud  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio           integer NOT NULL,
    fecha              date NOT NULL,
    peso               numeric(5,2),
    altura             numeric(3,2),
    grasa_corporal     numeric(4,2),
    masa_muscular      numeric(5,2),
    observaciones      text
);

COMMENT ON TABLE "Registro_Salud" IS
'HISTORICO 1:N. El indice unico (id_socio, fecha) impide dos mediciones el mismo
dia pero conserva toda la progresion.
altura se conserva a proposito: el gimnasio acepta MENORES, y en un adolescente la
altura si cambia entre mediciones. En un padron solo de adultos habria sido
redundante, porque dependeria de la persona y no del registro.';


-- =============================================================================
-- 4. DINERO
-- =============================================================================
-- POLITICA (decision de negocio, el esquema la refleja):
--   · PREPAGO. Se paga y se entra. Sin debito automatico ni suscripcion.
--   · Perjuicio del gimnasio (cierre, refaccion) -> NO se devuelve plata: se
--     CONGELA con origen = 'GIMNASIO' y se extiende el vencimiento.
--   · Baja voluntaria a mitad de periodo -> no hay devolucion ni congelamiento.
--   · Devolucion solo cuando no hay servicio que extender (ej. cobro duplicado),
--     y siempre TOTAL sobre la fila. NO hay reembolsos parciales, por diseno.
--
-- NO HAY TABLA DE DEUDAS: sin membresia activa no hay acceso, y el estado "debe"
-- es derivable. No necesita fila propia.

CREATE TABLE "Tipo_Membresia" (
    id_tipo_membresia  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre             character varying(50) NOT NULL UNIQUE,
    descripcion        text,
    duracion_dias      integer NOT NULL,
    precio_actual      numeric(10,2) NOT NULL,
    activo             boolean DEFAULT true
);

COMMENT ON TABLE "Tipo_Membresia" IS
'3FN: saca la dependencia transitiva Tipo -> Precio fuera de Membresia.
PENDIENTE: faltan CHECK duracion_dias > 0 y precio_actual >= 0.';


CREATE TABLE "Membresia" (
    id_membresia        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio            integer NOT NULL,
    id_tipo_membresia   integer NOT NULL,
    precio_pactado      numeric(10,2) NOT NULL,
    fecha_inicio        date NOT NULL,
    fecha_vencimiento   date,
    estado              estado_membresia NOT NULL DEFAULT 'ACTIVA'
);

COMMENT ON TABLE "Membresia" IS
'1:N con Socio -> historial de renovaciones.
precio_pactado (historico) != Tipo_Membresia.precio_actual (vigente). NO viola 3FN:
son dos hechos distintos, lo que se cobro entonces y lo que se cobra hoy.

INDICE PARCIAL membresia_una_activa_uidx: un socio tiene UNA sola membresia activa
a la vez. Es critico porque Congelamiento cuelga de aca: dos activas romperian toda
la logica de congelamiento y de extension de vencimiento.

estado es NOT NULL a proposito: un enum con NULL admite un valor fuera del dominio
declarado, y ademas las filas con NULL se ESCAPAN del indice parcial, porque un
indice con WHERE solo indexa las filas que cumplen la condicion.

SIN COBROS POR ADELANTADO (2026-09-16): con un periodo en curso (ACTIVA sin vencer o
SUSPENDIDA) no se cobra otro; la membresia nueva nace el dia del cobro. Asi nunca hay
dos ACTIVA simultaneas. Ver backend/renovacion.py y Pago.es_adelanto.
PENDIENTE: falta CHECK fecha_vencimiento >= fecha_inicio.';


CREATE TABLE "Congelamiento" (
    id_congelamiento    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_membresia        integer NOT NULL,
    fecha_inicio        date NOT NULL,
    fecha_fin           date NOT NULL,
    fecha_reanudacion   date,
    motivo              character varying(200),
    estado              estado_congelamiento NOT NULL DEFAULT 'ACTIVO',
    fecha_solicitud     timestamp without time zone NOT NULL DEFAULT now(),
    origen              origen_congelamiento NOT NULL DEFAULT 'SOCIO',

    CONSTRAINT chk_congelamiento_rango CHECK (fecha_fin >= fecha_inicio)
);

COMMENT ON TABLE "Congelamiento" IS
'Pausas de membresia. Al reanudar se extiende Membresia.fecha_vencimiento por los
dias REALMENTE congelados, no por los pedidos: por eso fecha_fin es lo previsto y
fecha_reanudacion lo efectivo.

origen distingue SOCIO (viaje, lesion) de GIMNASIO (cierre, refaccion). Se mantiene
porque los dias impuestos por el gimnasio NO deben contar contra un eventual tope
anual de congelamiento voluntario: seria cobrarle al socio un cierre que no fue
culpa suya.

ABIERTO — regla de solapados, definida pero NO implementada: cuando llega uno nuevo
y ya hay otro activo, se conserva el de fecha de fin MAS LEJANA. Si el nuevo termina
antes, se guarda como CANCELADO. Si termina despues, se corta el actual
(fecha_reanudacion = inicio del nuevo, estado FINALIZADO) y arranca el nuevo. Cortar
no es borrar: los dias ya vividos se acreditan. Los dos pasos van en una transaccion,
con el UPDATE antes del INSERT. Sin esto, el indice unico rechaza el segundo
congelamiento y el socio queda sin compensacion.';


CREATE TABLE "Promocion" (
    id_promocion          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_dueno              integer NOT NULL,
    id_sede               integer,
    nombre                character varying(100) NOT NULL,
    descripcion           text,
    porcentaje_descuento  numeric(5,2) NOT NULL,
    fecha_inicio          date NOT NULL,
    fecha_fin             date NOT NULL,
    activo                boolean DEFAULT true,

    CONSTRAINT chk_promocion_porcentaje CHECK (porcentaje_descuento > 0 AND porcentaje_descuento <= 100),
    CONSTRAINT chk_promocion_vigencia   CHECK (fecha_fin >= fecha_inicio)
);

COMMENT ON TABLE "Promocion" IS
'DFD 2.2. id_sede NULL = promocion global, aplica a todas las sedes.
El descuento es SIEMPRE porcentual: el de monto fijo se elimino por decision
comercial. Los pesos efectivamente descontados viven en Pago.monto_descuento.';

COMMENT ON COLUMN "Promocion".id_dueno IS
'Dueno que creo la promocion. NO se puede derivar de la sede porque las promociones
globales tienen id_sede NULL. Cuando id_sede no es NULL, la FK compuesta
fk_promocion_sede_dueno obliga a que coincida con Sede.id_dueno, asi que los dos
caminos nunca divergen: es redundancia CONTROLADA POR RESTRICCION, no libre.';


CREATE TABLE "Pago" (
    id_pago             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio            integer NOT NULL,
    id_membresia        integer,
    id_tipo_membresia   integer,
    id_inscripcion      integer,
    id_sede             integer,
    metodo              metodo_pago NOT NULL,
    monto               numeric(10,2) NOT NULL,
    fecha_pago          timestamp without time zone NOT NULL DEFAULT now(),
    periodo_desde       date,
    periodo_hasta       date,
    es_adelanto         boolean NOT NULL DEFAULT false,
    estado              estado_pago NOT NULL DEFAULT 'CONFIRMADO',
    fecha_cancelacion   timestamp without time zone,
    numero_comprobante  character varying(50) UNIQUE,
    id_promocion        integer,
    monto_descuento     numeric(10,2),

    -- Un pago adelantado sin periodo declarado no dice que esta cubriendo.
    CONSTRAINT chk_pago_adelanto_periodo CHECK (NOT es_adelanto OR periodo_desde IS NOT NULL)
);

COMMENT ON TABLE "Pago" IS
'DFD 2.1. Un pago NUNCA se borra: se marca CANCELADO o REEMBOLSADO.
monto_descuento se GUARDA y no se recalcula: la promocion puede cambiar o vencer
despues, y hay que poder reconstruir que se cobro ese dia.
ABIERTO — FK redundantes: id_socio es derivable via id_membresia o id_inscripcion,
e id_sede es derivable de Socio.id_sede. Nada garantiza hoy que coincidan.
PENDIENTE: falta CHECK monto >= 0, y definir si un pago puede cubrir membresia e
inscripcion a la vez o siempre una sola cosa.';

COMMENT ON COLUMN "Pago".es_adelanto IS
'Siempre false desde 2026-09-16: no se cobran periodos por adelantado (quien paga
meses adelantados congela el precio y el gimnasio pierde con cada aumento). Se
conserva por los pagos historicos y por chk_pago_adelanto_periodo.';

COMMENT ON COLUMN "Pago".id_tipo_membresia IS
'Plan de membresia que se cobro. NULL si el pago no es de una cuota (abono de
actividad, clase suelta). No alcanza con id_membresia: el pago online nace PENDIENTE
y sin membresia, que se crea recien al acreditarse y tiene que saber de que plan.
Antes se deducia buscando un plan con el mismo precio, y dos planes al mismo precio
(o un precio que cambio en el medio) lo confundian.';


-- =============================================================================
-- 5. ACTIVIDADES Y TURNOS
-- =============================================================================

CREATE TABLE "Actividad" (
    id_actividad                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                          character varying(80) NOT NULL UNIQUE,
    descripcion                     text,
    cupo_default                    integer NOT NULL,
    horas_anticipacion_cancelacion  integer NOT NULL DEFAULT 0,
    minutos_tolerancia              integer NOT NULL DEFAULT 15,
    activo                          boolean DEFAULT true,

    CONSTRAINT chk_actividad_tolerancia CHECK (minutos_tolerancia >= 0 AND minutos_tolerancia <= 180)
);

COMMENT ON TABLE "Actividad" IS
'Catalogo de lo que se puede reservar en un Turno.
Musculacion es una fila MAS aca, no un caso aparte: asi todo el sistema de turnos,
reservas e inscripciones funciona igual para las tres actividades sin duplicar
logica. Sus particularidades se expresan como DATOS: 0 horas de anticipacion
(acceso libre) y turnos que pueden no tener nadie a cargo.

minutos_tolerancia y horas_anticipacion_cancelacion son COLUMNAS y no constantes del
codigo: si el dueno tiene que llamar a un programador para cambiar algo suyo, el
dato esta mal ubicado.

ABIERTO: hoy el codigo detecta el acceso libre por el NOMBRE Musculacion, que es
fragil. Alternativas: usar horas_anticipacion_cancelacion = 0, o agregar una columna
es_acceso_libre configurable desde la app.';


CREATE TABLE "Plan_Actividad" (
    id_plan_actividad  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_actividad       integer NOT NULL,
    nombre             character varying(80) NOT NULL,
    tipo_limite        tipo_limite NOT NULL,
    cantidad           integer NOT NULL,
    precio             numeric(10,2) NOT NULL,
    activo             boolean DEFAULT true
);

COMMENT ON TABLE "Plan_Actividad" IS
'Formatos de venta de una Actividad. 1:N, NO se unifica con Actividad: unificarlas
repetiria los atributos de la actividad en cada plan y dejaria a Turno sin saber a
que fila apuntar.
POR_SEMANA   -> cantidad = veces por semana.
POR_MES      -> cantidad = clases totales del mes.
CLASE_SUELTA -> cantidad = 1. Es un plan mas del catalogo, no una columna aparte.
Los precios son FILAS y no constantes: el dueno los cambia sin tocar codigo.
PENDIENTE: falta CHECK precio >= 0.';


CREATE TABLE "Profesor_Actividad" (
    id_profesor   integer NOT NULL,
    id_actividad  integer NOT NULL,

    PRIMARY KEY (id_profesor, id_actividad)
);

COMMENT ON TABLE "Profesor_Actividad" IS
'N:M pura: que profesor esta habilitado para dictar que actividad.
Sirve de DESTINO a las FK compuestas de Turno y Horario_Actividad, que es como la
base garantiza que nadie quede a cargo de una actividad para la que no esta
habilitado.
ABIERTO: solo habilita PROFESORES. Los entrenadores no tienen control equivalente.
No molesta mientras esten solo a cargo de musculacion.';


CREATE TABLE "Horario_Actividad" (
    id_horario_actividad   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sede                integer NOT NULL,
    id_actividad           integer NOT NULL,
    dia_semana             integer NOT NULL,
    hora                   time without time zone NOT NULL,
    cupo                   integer NOT NULL,
    vigente_desde          date NOT NULL,
    vigente_hasta          date,
    activo                 boolean DEFAULT true,
    id_profesor            integer,
    id_entrenador_a_cargo  integer,

    CONSTRAINT chk_horario_cupo       CHECK (cupo > 0),
    CONSTRAINT chk_horario_dia_semana CHECK (dia_semana >= 1 AND dia_semana <= 7),
    CONSTRAINT chk_horario_vigencia   CHECK (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde),

    -- Ambas NULL es valido: sala de acceso libre sin nadie a cargo.
    CONSTRAINT chk_horario_un_solo_staff
        CHECK (NOT (id_entrenador_a_cargo IS NOT NULL AND id_profesor IS NOT NULL)),

    -- Clave candidata necesaria para la FK compuesta de habilitacion.
    CONSTRAINT horario_id_actividad_uk UNIQUE (id_horario_actividad, id_actividad)
);

COMMENT ON TABLE "Horario_Actividad" IS
'Horario semanal de cada actividad. Es la PLANTILLA: el backend genera los Turno de
las proximas semanas a partir de aca, en lugar de que alguien los cargue uno por uno.';


CREATE TABLE "Turno" (
    id_turno               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sede                integer NOT NULL,
    id_actividad           integer NOT NULL,
    fecha                  date NOT NULL,
    hora                   time without time zone NOT NULL,
    cupo_maximo            integer NOT NULL,
    estado                 estado_turno NOT NULL DEFAULT 'HABILITADO',
    id_horario_actividad   integer,
    motivo_cancelacion     character varying(200),
    observaciones          character varying(200),
    id_profesor            integer,
    id_entrenador_a_cargo  integer,

    -- Ambas NULL es valido: sala libre sin nadie a cargo.
    CONSTRAINT chk_turno_un_solo_staff
        CHECK (NOT (id_entrenador_a_cargo IS NOT NULL AND id_profesor IS NOT NULL))
);

COMMENT ON TABLE "Turno" IS
'La INSTANCIA concreta: una actividad con horario, en una fecha y sede.
hora es SOLO de llegada, no hay hora de fin.
id_entrenador_a_cargo es para musculacion; id_profesor para el resto. Las dos
columnas NO se unifican en una sola FK: se probo y se revirtio.
id_horario_actividad NULL = turno cargado a mano. La generacion automatica no lo toca.
ABIERTO — FK redundantes: cuando id_horario_actividad no es NULL, id_sede e
id_actividad son derivables del horario que genero el turno, y hoy nada impide que
se contradigan.
PENDIENTE: falta CHECK cupo_maximo > 0. Horario_Actividad.cupo si lo tiene.';


CREATE TABLE "Inscripcion_Actividad" (
    id_inscripcion      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio            integer NOT NULL,
    id_plan_actividad   integer NOT NULL,
    precio_pactado      numeric(10,2) NOT NULL,
    fecha_inicio        date NOT NULL,
    fecha_vencimiento   date NOT NULL,
    estado              estado_inscripcion NOT NULL DEFAULT 'ACTIVA'
);

COMMENT ON TABLE "Inscripcion_Actividad" IS
'Lo que un socio COMPRO de un Plan_Actividad.
precio_pactado es historico: el vigente vive en Plan_Actividad.precio y puede cambiar
despues. No viola 3FN, son dos hechos distintos.
clases_restantes fue ELIMINADA: el consumo se calcula al vuelo contando Reserva.
Guardarlo creaba una segunda fuente de verdad, y ademas dejaba dos criterios opuestos
en la misma columna (POR_MES lo guardaba, POR_SEMANA lo calculaba).
PENDIENTE: falta CHECK fecha_vencimiento >= fecha_inicio.';


CREATE TABLE "Reserva" (
    id_reserva          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_turno            integer NOT NULL,
    id_socio            integer NOT NULL,
    id_inscripcion      integer,
    id_pago             integer,
    fecha_reserva       timestamp without time zone DEFAULT now(),
    estado              estado_reserva NOT NULL DEFAULT 'RESERVADA',
    fecha_cancelacion   timestamp without time zone
);

COMMENT ON TABLE "Reserva" IS
'DFD 5.2. El indice unico (id_turno, id_socio) impide que un socio reserve DOS VECES
EL MISMO TURNO. NO limita cuantos turnos distintos reserva en un mismo dia: si esa
restriccion hace falta, es una regla aparte y todavia no esta definida.

id_inscripcion NULL = clase suelta. Reemplaza a un viejo booleano es_clase_suelta,
que repetia este mismo dato.

TRIGGER trg_reserva_cupo: no se reserva sobre un turno lleno.
TRIGGER trg_reserva_coherente: la inscripcion usada tiene que ser del mismo socio y
de la misma actividad que el turno.

estado es NOT NULL a proposito. El trigger de cupo arranca con
  IF NEW.estado IS DISTINCT FROM RESERVADA THEN RETURN NULL
y como NULL IS DISTINCT FROM RESERVADA da verdadero en logica de tres valores, una
reserva con estado nulo se salteaba la validacion de cupo Y tampoco se contaba
despues: entraba sin control y dejaba entrar a las demas.';


CREATE TABLE "Asistencia" (
    id_asistencia        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio             integer NOT NULL,
    id_sede              integer NOT NULL,
    id_reserva           integer,
    fecha_hora_ingreso   timestamp without time zone NOT NULL,
    fecha_hora_egreso    timestamp without time zone,
    metodo_registro      metodo_registro NOT NULL DEFAULT 'MANUAL',
    id_registrado_por    integer
);

COMMENT ON TABLE "Asistencia" IS
'1:N con Reserva: el socio puede entrar y salir varias veces por dia.
No existen estados ASISTIO / AUSENTE: se DEDUCEN de si hay o no fila aca.
ABIERTO — id_sede es TRIPLEMENTE derivable: de Socio.id_sede y, cuando hay reserva,
de Turno.id_sede. Tres fuentes para el mismo hecho, ninguna atada a las otras.
ABIERTO — contradiccion de politica: hay un docstring en backend/routers/asistencia.py
("EL SISTEMA INFORMA, NO JUZGA") que registra el ingreso igual con la cuota vencida.
Eso describe un modelo de FIADO y contradice la politica de que sin membresia activa
no hay acceso. Es la contradiccion mas importante que queda sin resolver.';


-- =============================================================================
-- 6. RUTINAS — plantilla y realidad
-- =============================================================================
-- Las rutinas son PLANTILLAS, no documentos personalizados: se escriben una vez y
-- se asignan a varios socios. Por eso el progreso real no puede vivir en la
-- plantilla, y va en Registro_Ejercicio.

CREATE TABLE "Ejercicio" (
    id_ejercicio      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            character varying(100) NOT NULL UNIQUE,
    grupo_muscular    character varying(50) NOT NULL,
    descripcion       text,
    url_video         character varying(255),
    requiere_maquina  boolean DEFAULT false
);

COMMENT ON TABLE "Ejercicio" IS
'3FN: grupo_muscular depende del EJERCICIO, no de la rutina en que aparece.
PENDIENTE: grupo_muscular es varchar libre pero TIENE UN INDICE ENCIMA, lo cual
prueba que se filtra por el: es un catalogo que no se declaro como tal. Sin
restriccion, Pecho, pecho y PECHO son tres grupos distintos.';


CREATE TABLE "Rutina" (
    id_rutina        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entrenador    integer,
    nombre           character varying(100) NOT NULL,
    objetivo         character varying(100),
    nivel            character varying(20),
    dias_por_semana  integer,
    fecha_creacion   date DEFAULT CURRENT_DATE,
    activo           boolean DEFAULT true
);

COMMENT ON TABLE "Rutina" IS
'DFD 3.1. PLANTILLA de un entrenador: se escribe una vez y se asigna a varios
socios.
id_entrenador NULL = RUTINA PROPIA de un socio: se la arma el mismo para si, sin
entrenador. El dueno NO se guarda aca (no hay id_socio): se DERIVA de la
Asignacion_Rutina, porque una rutina propia se asigna exactamente a su autor y a
nadie mas. Es invisible para el personal: los endpoints del staff (listar,
obtener, asignar, editar, baja) tratan id_entrenador NULL como inexistente, asi
que una rutina propia jamas aparece en el catalogo de rutinas a asignar.
PENDIENTE: nivel es varchar libre, deberia ser enum.';


CREATE TABLE "Rutina_Ejercicio" (
    id_rutina_ejercicio  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rutina            integer NOT NULL,
    id_ejercicio         integer NOT NULL,
    dia                  integer NOT NULL,
    orden                integer NOT NULL,
    series               integer,
    repeticiones         character varying(20),
    peso_sugerido        numeric(6,2),
    descanso_segundos    integer,
    observaciones        character varying(200)
);

COMMENT ON TABLE "Rutina_Ejercicio" IS
'1FN: una rutina tiene muchos ejercicios, asi que no pueden ser columnas.
peso_hecho NO puede ir aca: esta fila es de la PLANTILLA y la comparten todos los
socios que siguen esa rutina, asi que un peso aca no tendria dueno. Va en
Registro_Ejercicio, cuyo grano es (socio, ejercicio, fecha).';


CREATE TABLE "Asignacion_Rutina" (
    id_asignacion_rutina  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio              integer NOT NULL,
    id_rutina             integer NOT NULL,
    fecha_inicio          date NOT NULL,
    fecha_fin             date,
    estado                estado_asignacion NOT NULL DEFAULT 'ACTIVA'
);

COMMENT ON TABLE "Asignacion_Rutina" IS
'PK subrogada: permite historial y varias rutinas por socio a lo largo del tiempo.
INDICE PARCIAL asignacion_rutina_una_activa_uidx: un socio no puede tener dos rutinas
VIGENTES a la vez. El historial no cuenta, para eso el indice es parcial. Sin el
WHERE diria "una sola rutina en toda su vida", que seria absurdo.';


CREATE TABLE "Registro_Ejercicio" (
    id_registro_ejercicio  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio               integer NOT NULL,
    id_ejercicio           integer NOT NULL,
    fecha                  date NOT NULL DEFAULT CURRENT_DATE,
    peso_hecho             numeric(6,2) NOT NULL,
    series_hechas          integer,
    repeticiones_hechas    character varying(20),
    observaciones          character varying(200),

    CONSTRAINT chk_registro_ejercicio_peso CHECK (peso_hecho >= 0)
);

COMMENT ON TABLE "Registro_Ejercicio" IS
'Peso que el socio EFECTIVAMENTE levanto, cargado por el. Record = MAX(peso_hecho).
Es la mitad REAL del par plantilla/realidad: Rutina_Ejercicio dice que deberia hacer,
esto dice que hizo.
El indice (id_socio, id_ejercicio) fue ELIMINADO: era prefijo exacto del unico de
tres columnas. Un B-tree se recorre por sus columnas iniciales, asi que el de tres ya
resolvia todo lo que resolvia el de dos.';


CREATE TABLE "Asignacion_Entrenador" (
    id_asignacion_entrenador  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio                  integer NOT NULL,
    id_entrenador             integer NOT NULL,
    fecha_inicio              date NOT NULL,
    fecha_fin                 date,
    estado                    estado_asignacion NOT NULL DEFAULT 'ACTIVA'
);

COMMENT ON TABLE "Asignacion_Entrenador" IS
'Historiza el vinculo Socio - Entrenador.
ASIMETRIA DELIBERADA: a diferencia de Asignacion_Rutina y Asignacion_Dieta, NO tiene
indice de "una sola activa por socio". Un socio SI puede tener varios entrenadores a
la vez (musculacion + funcional). No es un olvido.';


-- =============================================================================
-- 7. DIETAS — plantilla y realidad
-- =============================================================================
-- Estructuralmente gemelas a las rutinas:
--   Rutina -> Rutina_Ejercicio -> Asignacion_Rutina -> Registro_Ejercicio
--   Dieta  -> Comida           -> Asignacion_Dieta  -> Registro_Comida

CREATE TABLE "Catalogo_Comida" (
    id_catalogo_comida  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              character varying(120) NOT NULL UNIQUE,
    descripcion         text,
    calorias            integer,
    activo              boolean DEFAULT true
);

COMMENT ON TABLE "Catalogo_Comida" IS
'Catalogo de platos. Las calorias, el nombre y la descripcion viven ACA porque
dependen del PLATO, no de la dieta ni del dia en que aparece. Es exactamente la
razon por la que Comida.calorias y Comida.descripcion fueron eliminadas.';


CREATE TABLE "Dieta" (
    id_dieta           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nutricionista   integer,
    nombre             character varying(100) NOT NULL,
    objetivo           character varying(100),
    calorias_diarias   integer,
    descripcion        text,
    fecha_creacion     date DEFAULT CURRENT_DATE,
    activo             boolean DEFAULT true
);

COMMENT ON TABLE "Dieta" IS
'DFD 4.1. Es una PLANTILLA, igual que Rutina.
id_nutricionista NULL = DIETA PROPIA de un socio: se la arma el mismo, sin
nutricionista. El dueno se DERIVA de Asignacion_Dieta (se asigna solo a su autor),
igual que Rutina.id_entrenador NULL para la rutina propia. Es invisible para el
personal: los endpoints del staff tratan id_nutricionista NULL como inexistente.';

COMMENT ON COLUMN "Dieta".calorias_diarias IS
'Objetivo calorico diario pautado por el nutricionista. NO es la suma de
Comida.calorias: es la intencion clinica, no el contenido. Que la suma real difiera
del objetivo es informacion valida, no una inconsistencia. Por eso no viola la regla
de "no guardar lo derivable": no es derivable de nada.';


CREATE TABLE "Comida" (
    id_comida           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_dieta            integer NOT NULL,
    dia                 integer,
    momento             character varying(30),
    id_catalogo_comida  integer,
    descripcion         character varying(200),

    -- Una comida sirve para algo solo si dice QUE comer: o sale del catalogo,
    -- o la describe el socio con texto libre. Al menos una de las dos.
    CONSTRAINT chk_comida_plato CHECK (id_catalogo_comida IS NOT NULL OR descripcion IS NOT NULL)
);

COMMENT ON TABLE "Comida" IS
'1FN: una dieta tiene varias comidas, asi que no pueden ser columnas.
El plato sale de Catalogo_Comida (id_catalogo_comida) O, cuando la dieta es PROPIA
del socio (Dieta.id_nutricionista NULL) y el catalogo del gimnasio esta vacio o no
tiene ese plato, de descripcion (texto libre). El CHECK exige al menos una de las
dos: una comida sin plato no dice nada.
Historia: id_catalogo_comida fue OBLIGATORIO un tiempo (y por eso calorias y
descripcion se habian eliminado); se volvio opcional al habilitar la dieta propia,
y descripcion volvio como texto libre del plan (NO son calorias: el contenido real
va en Registro_Comida).
PENDIENTE: momento es varchar libre, deberia ser enum.';


CREATE TABLE "Asignacion_Dieta" (
    id_asignacion_dieta  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio             integer NOT NULL,
    id_dieta             integer NOT NULL,
    fecha_inicio         date NOT NULL,
    fecha_fin            date,
    estado               estado_asignacion NOT NULL DEFAULT 'ACTIVA',
    observaciones        text
);

COMMENT ON TABLE "Asignacion_Dieta" IS
'Almacen "Dietas asignadas" del DFD 4.2. Entidad asociativa HISTORIZADA entre Socio y
Dieta: no es una N:M pura porque tiene PK subrogada y atributos propios (vigencia,
estado, observaciones), lo que permite conservar el historial de asignaciones y no
solo el vinculo actual.';


CREATE TABLE "Registro_Comida" (
    id_registro_comida  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio            integer NOT NULL,
    id_comida           integer,
    fecha               date NOT NULL DEFAULT CURRENT_DATE,
    comida_ingerida     text NOT NULL,
    momento             character varying(30),
    calorias_estimadas  integer,
    -- Macros de lo REALMENTE comido. Los carga el socio a mano, o los completa
    -- el coach IA a partir del texto de comida_ingerida (opcional: si no hay IA
    -- ni el socio los pone, quedan NULL y el registro vale igual por el texto).
    proteinas_g         numeric(6,2),
    carbohidratos_g     numeric(6,2),
    grasas_g            numeric(6,2)
);

COMMENT ON TABLE "Registro_Comida" IS
'Lo que el socio REALMENTE comio un dia, cargado por el.
Es a Comida lo que Registro_Ejercicio es a Rutina_Ejercicio: PLANTILLA contra
REALIDAD. No puede ir como columna de Comida porque esa fila pertenece a la plantilla
Dieta y la comparten todos los socios que la siguen; ademas necesita fecha.
id_comida = que comida de la dieta CORRESPONDIA. comida_ingerida = que comio DE
VERDAD. Son dos hechos distintos: el socio pudo comer algo diferente de lo
planificado, y registrar esa diferencia es el proposito de la tabla.';

COMMENT ON COLUMN "Registro_Comida".comida_ingerida IS
'Texto libre: que comio realmente. Deliberadamente NO apunta a Catalogo_Comida, para
que el socio pueda anotar cualquier cosa sin depender del catalogo del nutricionista.
Es NOT NULL porque una fila que no dice que comio no sirve para nada.
CONSECUENCIA A TENER PRESENTE: sin vinculo al catalogo no se pueden cruzar calorias
reales automaticamente ni sacar estadisticas de platos mas consumidos.
calorias_estimadas queda como unica fuente calorica de lo ingerido.';

COMMENT ON COLUMN "Registro_Comida".calorias_estimadas IS
'Calorias que el SOCIO estima haber ingerido ese dia. Es lo que separa lo pautado de
lo efectivamente consumido: el socio pudo comer media porcion, el doble, o algo
distinto de lo planificado.';


-- =============================================================================
-- 8. CLAVES FORÁNEAS
-- =============================================================================
-- 66 en total: 64 simples y 2 compuestas. Todas DEFERRABLE, ninguna con ON DELETE.

-- --- Persona hacia sus datos de contacto y su usuario ---
ALTER TABLE "Telefono"            ADD CONSTRAINT "Telefono_id_persona_fkey"            FOREIGN KEY (id_persona) REFERENCES "Persona"(id_persona) DEFERRABLE;
ALTER TABLE "Contacto_Emergencia" ADD CONSTRAINT "Contacto_Emergencia_id_persona_fkey" FOREIGN KEY (id_persona) REFERENCES "Persona"(id_persona) DEFERRABLE;
ALTER TABLE "Usuario"             ADD CONSTRAINT "Usuario_id_persona_fkey"             FOREIGN KEY (id_persona) REFERENCES "Persona"(id_persona) DEFERRABLE;

-- --- Persona hacia sus roles ---
ALTER TABLE "Dueno"    ADD CONSTRAINT "Dueno_id_persona_fkey"    FOREIGN KEY (id_persona) REFERENCES "Persona"(id_persona) DEFERRABLE;
ALTER TABLE "Empleado" ADD CONSTRAINT "Empleado_id_persona_fkey" FOREIGN KEY (id_persona) REFERENCES "Persona"(id_persona) DEFERRABLE;
ALTER TABLE "Socio"    ADD CONSTRAINT "Socio_id_persona_fkey"    FOREIGN KEY (id_persona) REFERENCES "Persona"(id_persona) DEFERRABLE;

-- --- Estructura organizativa ---
ALTER TABLE "Sede"     ADD CONSTRAINT "Sede_id_dueno_fkey"    FOREIGN KEY (id_dueno) REFERENCES "Dueno"(id_dueno) DEFERRABLE;
ALTER TABLE "Empleado" ADD CONSTRAINT "Empleado_id_sede_fkey" FOREIGN KEY (id_sede)  REFERENCES "Sede"(id_sede)   DEFERRABLE;
ALTER TABLE "Socio"    ADD CONSTRAINT "Socio_id_sede_fkey"    FOREIGN KEY (id_sede)  REFERENCES "Sede"(id_sede)   DEFERRABLE;

-- --- Subtipos de Empleado (solapados) ---
ALTER TABLE "Entrenador"    ADD CONSTRAINT "Entrenador_id_empleado_fkey"    FOREIGN KEY (id_empleado) REFERENCES "Empleado"(id_empleado) DEFERRABLE;
ALTER TABLE "Profesor"      ADD CONSTRAINT "Profesor_id_empleado_fkey"      FOREIGN KEY (id_empleado) REFERENCES "Empleado"(id_empleado) DEFERRABLE;
ALTER TABLE "Nutricionista" ADD CONSTRAINT "Nutricionista_id_empleado_fkey" FOREIGN KEY (id_empleado) REFERENCES "Empleado"(id_empleado) DEFERRABLE;
ALTER TABLE "Recepcionista" ADD CONSTRAINT "Recepcionista_id_empleado_fkey" FOREIGN KEY (id_empleado) REFERENCES "Empleado"(id_empleado) DEFERRABLE;
ALTER TABLE "Recepcionista" ADD CONSTRAINT "Recepcionista_id_franja_laboral_fkey" FOREIGN KEY (id_franja_laboral) REFERENCES "Franja_Laboral"(id_franja_laboral) DEFERRABLE;

-- --- Socio ---
ALTER TABLE "Socio_Patologia" ADD CONSTRAINT "Socio_Patologia_id_socio_fkey"     FOREIGN KEY (id_socio)     REFERENCES "Socio"(id_socio)         DEFERRABLE;
ALTER TABLE "Socio_Patologia" ADD CONSTRAINT "Socio_Patologia_id_patologia_fkey" FOREIGN KEY (id_patologia) REFERENCES "Patologia"(id_patologia) DEFERRABLE;
ALTER TABLE "Baja"            ADD CONSTRAINT "Baja_id_socio_fkey"                FOREIGN KEY (id_socio)     REFERENCES "Socio"(id_socio)         DEFERRABLE;
ALTER TABLE "Registro_Salud"  ADD CONSTRAINT "Registro_Salud_id_socio_fkey"      FOREIGN KEY (id_socio)     REFERENCES "Socio"(id_socio)         DEFERRABLE;

-- --- Dinero ---
ALTER TABLE "Membresia"     ADD CONSTRAINT "Membresia_id_socio_fkey"          FOREIGN KEY (id_socio)          REFERENCES "Socio"(id_socio)                       DEFERRABLE;
ALTER TABLE "Membresia"     ADD CONSTRAINT "Membresia_id_tipo_membresia_fkey" FOREIGN KEY (id_tipo_membresia) REFERENCES "Tipo_Membresia"(id_tipo_membresia)     DEFERRABLE;
ALTER TABLE "Congelamiento" ADD CONSTRAINT "Congelamiento_id_membresia_fkey"  FOREIGN KEY (id_membresia)      REFERENCES "Membresia"(id_membresia)               DEFERRABLE;
ALTER TABLE "Pago"          ADD CONSTRAINT "Pago_id_socio_fkey"               FOREIGN KEY (id_socio)          REFERENCES "Socio"(id_socio)                       DEFERRABLE;
ALTER TABLE "Pago"          ADD CONSTRAINT "Pago_id_membresia_fkey"           FOREIGN KEY (id_membresia)      REFERENCES "Membresia"(id_membresia)               DEFERRABLE;
ALTER TABLE "Pago"          ADD CONSTRAINT "Pago_id_tipo_membresia_fkey"      FOREIGN KEY (id_tipo_membresia) REFERENCES "Tipo_Membresia"(id_tipo_membresia)     DEFERRABLE;
ALTER TABLE "Pago"          ADD CONSTRAINT "Pago_id_inscripcion_fkey"         FOREIGN KEY (id_inscripcion)    REFERENCES "Inscripcion_Actividad"(id_inscripcion) DEFERRABLE;
ALTER TABLE "Pago"          ADD CONSTRAINT "Pago_id_sede_fkey"                FOREIGN KEY (id_sede)           REFERENCES "Sede"(id_sede)                         DEFERRABLE;
ALTER TABLE "Pago"          ADD CONSTRAINT "Pago_id_promocion_fkey"           FOREIGN KEY (id_promocion)      REFERENCES "Promocion"(id_promocion)               DEFERRABLE;
ALTER TABLE "Promocion"     ADD CONSTRAINT "Promocion_id_dueno_fkey"          FOREIGN KEY (id_dueno)          REFERENCES "Dueno"(id_dueno)                       DEFERRABLE;

-- FK COMPUESTA 1 de 2. Reemplaza a la FK simple Promocion.id_sede -> Sede.
-- Aprovecha MATCH SIMPLE, el comportamiento por defecto del estandar SQL: si
-- alguna columna de una FK compuesta es NULL, la restriccion NO se verifica.
-- Como id_dueno es NOT NULL, la unica que puede faltar es id_sede, y la regla se
-- parte sola en dos ramas sin escribir logica condicional:
--   · con sede -> se valida que el dueno sea efectivamente el de esa sede
--   · sin sede (promocion global) -> la restriccion se desactiva sola
ALTER TABLE "Promocion"
    ADD CONSTRAINT fk_promocion_sede_dueno
    FOREIGN KEY (id_sede, id_dueno) REFERENCES "Sede"(id_sede, id_dueno) DEFERRABLE;

-- --- Actividades y turnos ---
ALTER TABLE "Plan_Actividad"     ADD CONSTRAINT "Plan_Actividad_id_actividad_fkey"          FOREIGN KEY (id_actividad)          REFERENCES "Actividad"(id_actividad)                       DEFERRABLE;
ALTER TABLE "Profesor_Actividad" ADD CONSTRAINT "Profesor_Actividad_id_profesor_fkey"       FOREIGN KEY (id_profesor)           REFERENCES "Profesor"(id_profesor)                         DEFERRABLE;
ALTER TABLE "Profesor_Actividad" ADD CONSTRAINT "Profesor_Actividad_id_actividad_fkey"      FOREIGN KEY (id_actividad)          REFERENCES "Actividad"(id_actividad)                       DEFERRABLE;
ALTER TABLE "Horario_Actividad"  ADD CONSTRAINT "Horario_Actividad_id_sede_fkey"            FOREIGN KEY (id_sede)               REFERENCES "Sede"(id_sede)                                 DEFERRABLE;
ALTER TABLE "Horario_Actividad"  ADD CONSTRAINT "Horario_Actividad_id_actividad_fkey"       FOREIGN KEY (id_actividad)          REFERENCES "Actividad"(id_actividad)                       DEFERRABLE;
ALTER TABLE "Horario_Actividad"  ADD CONSTRAINT "Horario_Actividad_id_entrenador_fkey"      FOREIGN KEY (id_entrenador_a_cargo) REFERENCES "Entrenador"(id_entrenador)                     DEFERRABLE;
ALTER TABLE "Turno"              ADD CONSTRAINT "Turno_id_sede_fkey"                        FOREIGN KEY (id_sede)               REFERENCES "Sede"(id_sede)                                 DEFERRABLE;
ALTER TABLE "Turno"              ADD CONSTRAINT "Turno_id_actividad_fkey"                   FOREIGN KEY (id_actividad)          REFERENCES "Actividad"(id_actividad)                       DEFERRABLE;
ALTER TABLE "Turno"              ADD CONSTRAINT "Turno_id_horario_actividad_fkey"           FOREIGN KEY (id_horario_actividad)  REFERENCES "Horario_Actividad"(id_horario_actividad)       DEFERRABLE;
ALTER TABLE "Turno"              ADD CONSTRAINT "Turno_id_entrenador_fkey"                  FOREIGN KEY (id_entrenador_a_cargo) REFERENCES "Entrenador"(id_entrenador)                     DEFERRABLE;

-- FK COMPUESTA 2 de 2. Garantiza que el profesor a cargo este HABILITADO para esa
-- actividad. Mismo mecanismo MATCH SIMPLE: si id_profesor es NULL (musculacion o
-- sala libre), la restriccion no se verifica.
-- Nota: solo controla PROFESORES. id_entrenador_a_cargo no tiene equivalente, y es
-- asi desde el esquema original: no es una regresion.
ALTER TABLE "Horario_Actividad"
    ADD CONSTRAINT fk_horario_profesor_habilitado
    FOREIGN KEY (id_profesor, id_actividad) REFERENCES "Profesor_Actividad"(id_profesor, id_actividad) DEFERRABLE;

ALTER TABLE "Turno"
    ADD CONSTRAINT fk_turno_profesor_habilitado
    FOREIGN KEY (id_profesor, id_actividad) REFERENCES "Profesor_Actividad"(id_profesor, id_actividad) DEFERRABLE;

-- --- Inscripciones, reservas y asistencia ---
ALTER TABLE "Inscripcion_Actividad" ADD CONSTRAINT "Inscripcion_Actividad_id_socio_fkey"          FOREIGN KEY (id_socio)          REFERENCES "Socio"(id_socio)                       DEFERRABLE;
ALTER TABLE "Inscripcion_Actividad" ADD CONSTRAINT "Inscripcion_Actividad_id_plan_actividad_fkey" FOREIGN KEY (id_plan_actividad) REFERENCES "Plan_Actividad"(id_plan_actividad)     DEFERRABLE;
ALTER TABLE "Reserva"               ADD CONSTRAINT "Reserva_id_turno_fkey"                        FOREIGN KEY (id_turno)          REFERENCES "Turno"(id_turno)                       DEFERRABLE;
ALTER TABLE "Reserva"               ADD CONSTRAINT "Reserva_id_socio_fkey"                        FOREIGN KEY (id_socio)          REFERENCES "Socio"(id_socio)                       DEFERRABLE;
ALTER TABLE "Reserva"               ADD CONSTRAINT "Reserva_id_inscripcion_fkey"                  FOREIGN KEY (id_inscripcion)    REFERENCES "Inscripcion_Actividad"(id_inscripcion) DEFERRABLE;
ALTER TABLE "Reserva"               ADD CONSTRAINT "Reserva_id_pago_fkey"                         FOREIGN KEY (id_pago)           REFERENCES "Pago"(id_pago)                         DEFERRABLE;
ALTER TABLE "Asistencia"            ADD CONSTRAINT "Asistencia_id_socio_fkey"                     FOREIGN KEY (id_socio)          REFERENCES "Socio"(id_socio)                       DEFERRABLE;
ALTER TABLE "Asistencia"            ADD CONSTRAINT "Asistencia_id_sede_fkey"                      FOREIGN KEY (id_sede)           REFERENCES "Sede"(id_sede)                         DEFERRABLE;
ALTER TABLE "Asistencia"            ADD CONSTRAINT "Asistencia_id_reserva_fkey"                   FOREIGN KEY (id_reserva)        REFERENCES "Reserva"(id_reserva)                   DEFERRABLE;
ALTER TABLE "Asistencia"            ADD CONSTRAINT "Asistencia_id_registrado_por_fkey"            FOREIGN KEY (id_registrado_por) REFERENCES "Usuario"(id_usuario)                   DEFERRABLE;

-- --- Rutinas ---
ALTER TABLE "Rutina"                ADD CONSTRAINT "Rutina_id_entrenador_fkey"                FOREIGN KEY (id_entrenador) REFERENCES "Entrenador"(id_entrenador) DEFERRABLE;
ALTER TABLE "Rutina_Ejercicio"      ADD CONSTRAINT "Rutina_Ejercicio_id_rutina_fkey"          FOREIGN KEY (id_rutina)     REFERENCES "Rutina"(id_rutina)         DEFERRABLE;
ALTER TABLE "Rutina_Ejercicio"      ADD CONSTRAINT "Rutina_Ejercicio_id_ejercicio_fkey"       FOREIGN KEY (id_ejercicio)  REFERENCES "Ejercicio"(id_ejercicio)   DEFERRABLE;
ALTER TABLE "Asignacion_Rutina"     ADD CONSTRAINT "Asignacion_Rutina_id_socio_fkey"          FOREIGN KEY (id_socio)      REFERENCES "Socio"(id_socio)           DEFERRABLE;
ALTER TABLE "Asignacion_Rutina"     ADD CONSTRAINT "Asignacion_Rutina_id_rutina_fkey"         FOREIGN KEY (id_rutina)     REFERENCES "Rutina"(id_rutina)         DEFERRABLE;
ALTER TABLE "Registro_Ejercicio"    ADD CONSTRAINT "Registro_Ejercicio_id_socio_fkey"         FOREIGN KEY (id_socio)      REFERENCES "Socio"(id_socio)           DEFERRABLE;
ALTER TABLE "Registro_Ejercicio"    ADD CONSTRAINT "Registro_Ejercicio_id_ejercicio_fkey"     FOREIGN KEY (id_ejercicio)  REFERENCES "Ejercicio"(id_ejercicio)   DEFERRABLE;
ALTER TABLE "Asignacion_Entrenador" ADD CONSTRAINT "Asignacion_Entrenador_id_socio_fkey"      FOREIGN KEY (id_socio)      REFERENCES "Socio"(id_socio)           DEFERRABLE;
ALTER TABLE "Asignacion_Entrenador" ADD CONSTRAINT "Asignacion_Entrenador_id_entrenador_fkey" FOREIGN KEY (id_entrenador) REFERENCES "Entrenador"(id_entrenador) DEFERRABLE;

-- --- Dietas ---
ALTER TABLE "Dieta"            ADD CONSTRAINT "Dieta_id_nutricionista_fkey"     FOREIGN KEY (id_nutricionista)   REFERENCES "Nutricionista"(id_nutricionista)     DEFERRABLE;
ALTER TABLE "Comida"           ADD CONSTRAINT "Comida_id_dieta_fkey"            FOREIGN KEY (id_dieta)           REFERENCES "Dieta"(id_dieta)                     DEFERRABLE;
ALTER TABLE "Comida"           ADD CONSTRAINT "Comida_id_catalogo_comida_fkey"  FOREIGN KEY (id_catalogo_comida) REFERENCES "Catalogo_Comida"(id_catalogo_comida) DEFERRABLE;
ALTER TABLE "Asignacion_Dieta" ADD CONSTRAINT "Asignacion_Dieta_id_socio_fkey"  FOREIGN KEY (id_socio)           REFERENCES "Socio"(id_socio)                     DEFERRABLE;
ALTER TABLE "Asignacion_Dieta" ADD CONSTRAINT "Asignacion_Dieta_id_dieta_fkey"  FOREIGN KEY (id_dieta)           REFERENCES "Dieta"(id_dieta)                     DEFERRABLE;
ALTER TABLE "Registro_Comida"  ADD CONSTRAINT "Registro_Comida_id_socio_fkey"   FOREIGN KEY (id_socio)           REFERENCES "Socio"(id_socio)                     DEFERRABLE;
ALTER TABLE "Registro_Comida"  ADD CONSTRAINT "Registro_Comida_id_comida_fkey"  FOREIGN KEY (id_comida)          REFERENCES "Comida"(id_comida)                   DEFERRABLE;


-- =============================================================================
-- 9. ÍNDICES
-- =============================================================================
-- Los que llevan WHERE son PARCIALES: sólo indexan las filas que cumplen la
-- condición. Es lo que convierte "una sola en toda su vida" en "una sola VIGENTE
-- a la vez" — sin el WHERE serían absurdos, porque el historial también cuenta.
--
-- IMPORTANTE: los índices parciales dependen de que la columna de estado sea
-- NOT NULL. Una fila con estado nulo no cumple la condición del WHERE, así que
-- queda FUERA del índice y convive con una activa sin disparar conflicto. Por eso
-- las ocho columnas de estado del esquema son obligatorias.

-- --- Contacto ---
CREATE INDEX contacto_emergencia_persona_idx ON "Contacto_Emergencia" (id_persona);

-- --- Socio ---
CREATE UNIQUE INDEX "Registro_Salud_id_socio_fecha_idx" ON "Registro_Salud" (id_socio, fecha);

-- --- Dinero ---
CREATE INDEX        "Membresia_estado_fecha_vencimiento_idx" ON "Membresia" (estado, fecha_vencimiento);
CREATE UNIQUE INDEX "Membresia_id_socio_fecha_inicio_idx"    ON "Membresia" (id_socio, fecha_inicio);

CREATE UNIQUE INDEX membresia_una_activa_uidx ON "Membresia" (id_socio)
    WHERE (estado = 'ACTIVA'::estado_membresia);
COMMENT ON INDEX membresia_una_activa_uidx IS
'Una sola membresia ACTIVA por socio. Parcial a proposito: el historial de
renovaciones (VENCIDA / CANCELADA) no cuenta.';

CREATE INDEX congelamiento_origen_idx ON "Congelamiento" (origen, fecha_inicio);
CREATE UNIQUE INDEX congelamiento_una_activa_uidx ON "Congelamiento" (id_membresia)
    WHERE (estado = 'ACTIVO'::estado_congelamiento);

CREATE INDEX "Pago_id_sede_fecha_pago_idx"  ON "Pago" (id_sede, fecha_pago);
CREATE INDEX "Pago_id_socio_fecha_pago_idx" ON "Pago" (id_socio, fecha_pago);

-- --- Actividades y turnos ---
CREATE INDEX horario_actividad_activo_idx ON "Horario_Actividad" (activo, dia_semana);
CREATE UNIQUE INDEX horario_actividad_unico_uidx
    ON "Horario_Actividad" (id_sede, id_actividad, dia_semana, hora) WHERE activo;

CREATE INDEX        "Turno_id_actividad_fecha_idx"              ON "Turno" (id_actividad, fecha);
CREATE UNIQUE INDEX "Turno_id_sede_id_actividad_fecha_hora_idx" ON "Turno" (id_sede, id_actividad, fecha, hora);
CREATE INDEX        turno_fecha_hora_estado_idx                 ON "Turno" (fecha, hora, estado);
CREATE INDEX        turno_horario_actividad_idx                 ON "Turno" (id_horario_actividad)
    WHERE (id_horario_actividad IS NOT NULL);

CREATE INDEX "Inscripcion_Actividad_id_socio_estado_idx" ON "Inscripcion_Actividad" (id_socio, estado);

CREATE INDEX        "Reserva_id_turno_estado_idx"  ON "Reserva" (id_turno, estado);
CREATE UNIQUE INDEX "Reserva_id_turno_id_socio_idx" ON "Reserva" (id_turno, id_socio);

CREATE INDEX "Asistencia_id_sede_fecha_hora_ingreso_idx"  ON "Asistencia" (id_sede, fecha_hora_ingreso);
CREATE INDEX "Asistencia_id_socio_fecha_hora_ingreso_idx" ON "Asistencia" (id_socio, fecha_hora_ingreso);
CREATE INDEX asistencia_reserva_idx ON "Asistencia" (id_reserva) WHERE (id_reserva IS NOT NULL);

-- --- Rutinas ---
CREATE INDEX "Ejercicio_grupo_muscular_idx" ON "Ejercicio" (grupo_muscular);
CREATE UNIQUE INDEX "Rutina_Ejercicio_id_rutina_dia_orden_idx" ON "Rutina_Ejercicio" (id_rutina, dia, orden);

CREATE INDEX        "Asignacion_Rutina_id_socio_estado_idx" ON "Asignacion_Rutina" (id_socio, estado);
CREATE UNIQUE INDEX "Asignacion_Rutina_id_socio_id_rutina_fecha_inicio_idx"
    ON "Asignacion_Rutina" (id_socio, id_rutina, fecha_inicio);
CREATE UNIQUE INDEX asignacion_rutina_una_activa_uidx ON "Asignacion_Rutina" (id_socio)
    WHERE (estado = 'ACTIVA'::estado_asignacion);

-- El indice (id_socio, id_ejercicio) fue eliminado: era prefijo exacto de este.
-- Un B-tree se recorre por sus columnas iniciales, asi que el de tres columnas ya
-- resolvia todo lo que resolvia el de dos, y tener los dos costaba espacio y
-- escrituras sin ninguna ganancia.
CREATE UNIQUE INDEX registro_ejercicio_socio_ej_fecha_uidx
    ON "Registro_Ejercicio" (id_socio, id_ejercicio, fecha);

CREATE UNIQUE INDEX asignacion_entrenador_socio_entrenador_fecha_uidx
    ON "Asignacion_Entrenador" (id_socio, id_entrenador, fecha_inicio);
CREATE INDEX asignacion_entrenador_socio_estado_idx ON "Asignacion_Entrenador" (id_socio, estado);

-- --- Dietas ---
CREATE INDEX "Comida_id_dieta_dia_idx" ON "Comida" (id_dieta, dia);

CREATE INDEX        "Asignacion_Dieta_id_socio_estado_idx" ON "Asignacion_Dieta" (id_socio, estado);
CREATE UNIQUE INDEX asignacion_dieta_socio_dieta_fecha_uidx
    ON "Asignacion_Dieta" (id_socio, id_dieta, fecha_inicio);
CREATE UNIQUE INDEX asignacion_dieta_una_activa_uidx ON "Asignacion_Dieta" (id_socio)
    WHERE (estado = 'ACTIVA'::estado_asignacion);

CREATE INDEX registro_comida_socio_fecha_idx ON "Registro_Comida" (id_socio, fecha);


-- =============================================================================
-- 10. FUNCIONES Y TRIGGERS
-- =============================================================================
-- Son triggers y no CHECK porque un CHECK sólo puede mirar la fila que se está
-- escribiendo, y estas reglas necesitan contar o consultar filas de OTRA tabla.
--
-- Todos son CONSTRAINT TRIGGER DIFERIDOS: validan al COMMIT y no al INSERT. Eso
-- permite operaciones de varios pasos dentro de una transacción — dar de alta un
-- Empleado y después su subtipo, o cancelar una reserva y promover a alguien de
-- la lista de espera — sin que la validación se dispare a mitad de camino sobre
-- un estado intermedio que todavía no es el final.

-- -----------------------------------------------------------------------------
-- 10.1 · Ningún empleado sin subtipo
-- -----------------------------------------------------------------------------
CREATE FUNCTION trg_empleado_debe_tener_subtipo() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_id_empleado int;
  v_existe      boolean;
  v_tiene       boolean;
BEGIN
  -- Empleado en riesgo de quedar colgado:
  --   INSERT en Empleado          -> NEW (el recién creado)
  --   DELETE/UPDATE en un subtipo -> OLD (el que perdió el rol)
  IF TG_TABLE_NAME = 'Empleado' THEN
    v_id_empleado := NEW.id_empleado;
  ELSE
    v_id_empleado := OLD.id_empleado;
  END IF;

  -- Si el empleado ya no existe (se borró en la misma tx), no exigimos nada.
  SELECT EXISTS(SELECT 1 FROM "Empleado" WHERE id_empleado = v_id_empleado)
    INTO v_existe;
  IF NOT v_existe THEN
    RETURN NULL;
  END IF;

  SELECT
       EXISTS(SELECT 1 FROM "Entrenador"    WHERE id_empleado = v_id_empleado)
    OR EXISTS(SELECT 1 FROM "Nutricionista" WHERE id_empleado = v_id_empleado)
    OR EXISTS(SELECT 1 FROM "Recepcionista" WHERE id_empleado = v_id_empleado)
    OR EXISTS(SELECT 1 FROM "Profesor"      WHERE id_empleado = v_id_empleado)
    INTO v_tiene;

  IF NOT v_tiene THEN
    RAISE EXCEPTION
      'Empleado % no tiene subtipo. Todo empleado debe ser al menos uno de: Entrenador, Nutricionista, Recepcionista o Profesor.',
      v_id_empleado
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_empleado_completo
    AFTER INSERT ON "Empleado"
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION trg_empleado_debe_tener_subtipo();

CREATE CONSTRAINT TRIGGER trg_entrenador_no_deja_colgado
    AFTER DELETE OR UPDATE OF id_empleado ON "Entrenador"
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION trg_empleado_debe_tener_subtipo();

CREATE CONSTRAINT TRIGGER trg_nutri_no_deja_colgado
    AFTER DELETE OR UPDATE OF id_empleado ON "Nutricionista"
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION trg_empleado_debe_tener_subtipo();

CREATE CONSTRAINT TRIGGER trg_profesor_no_deja_colgado
    AFTER DELETE OR UPDATE OF id_empleado ON "Profesor"
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION trg_empleado_debe_tener_subtipo();

CREATE CONSTRAINT TRIGGER trg_recep_no_deja_colgado
    AFTER DELETE OR UPDATE OF id_empleado ON "Recepcionista"
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION trg_empleado_debe_tener_subtipo();


-- -----------------------------------------------------------------------------
-- 10.2 · No se vende más allá del cupo
-- -----------------------------------------------------------------------------
CREATE FUNCTION trg_reserva_respeta_cupo() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_cupo      int;
  v_ocupados  int;
  v_actividad text;
BEGIN
  -- EN_ESPERA y las canceladas no ocupan lugar: por definicion la lista de
  -- espera existe para los que NO entraron. Si contaran, el turno se veria
  -- lleno con gente que no tiene lugar y la cola nunca avanzaria.
  IF NEW.estado IS DISTINCT FROM 'RESERVADA' THEN
    RETURN NULL;
  END IF;

  SELECT t.cupo_maximo, a.nombre
    INTO v_cupo, v_actividad
  FROM "Turno" t
  LEFT JOIN "Actividad" a ON a.id_actividad = t.id_actividad
  WHERE t.id_turno = NEW.id_turno;

  -- El turno pudo haberse borrado en la misma transaccion. No es asunto de
  -- este trigger: de eso se ocupa la foreign key.
  IF v_cupo IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT count(*) INTO v_ocupados
  FROM "Reserva"
  WHERE id_turno = NEW.id_turno AND estado = 'RESERVADA';

  IF v_ocupados > v_cupo THEN
    RAISE EXCEPTION
      'El turno % (%) tiene cupo % y ya hay % reservas confirmadas.',
      NEW.id_turno, coalesce(v_actividad, 'sin actividad'), v_cupo, v_ocupados
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_reserva_cupo
    AFTER INSERT OR UPDATE OF estado, id_turno ON "Reserva"
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION trg_reserva_respeta_cupo();


-- -----------------------------------------------------------------------------
-- 10.3 · No bajar el cupo por debajo de lo ya reservado
-- -----------------------------------------------------------------------------
CREATE FUNCTION trg_turno_cupo_no_menor_a_reservas() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_ocupados int;
BEGIN
  SELECT count(*) INTO v_ocupados
  FROM "Reserva"
  WHERE id_turno = NEW.id_turno AND estado = 'RESERVADA';

  IF v_ocupados > NEW.cupo_maximo THEN
    RAISE EXCEPTION
      'No se puede dejar el cupo del turno % en %: ya hay % personas anotadas.',
      NEW.id_turno, NEW.cupo_maximo, v_ocupados
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_turno_cupo
    AFTER UPDATE OF cupo_maximo ON "Turno"
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION trg_turno_cupo_no_menor_a_reservas();


-- -----------------------------------------------------------------------------
-- 10.4 · La inscripción usada tiene que corresponder [NUEVO]
-- -----------------------------------------------------------------------------
-- Cierra dos agujeros que estaban abiertos en Reserva:
--   1. Una inscripción a Yoga permitía reservar un turno de Boxeo.
--   2. Un socio podía consumir la inscripción de otro.
--
-- POR QUÉ UN TRIGGER Y NO UNA CLAVE FORÁNEA COMPUESTA. La alternativa era
-- propagar id_actividad hasta Reserva y atarla por los dos lados, que es la
-- técnica de fk_turno_profesor_habilitado. Se descartó para no agregar columnas:
-- la tabla queda exactamente como estaba.
--
-- LO QUE SE PIERDE CON ESTA ELECCIÓN, y conviene tenerlo presente: este trigger
-- vive en Reserva, así que sólo se dispara cuando se escribe una Reserva. Si más
-- adelante alguien cambia Plan_Actividad.id_actividad de un plan que ya tiene
-- inscripciones con reservas hechas, esas reservas quedan incoherentes y nada las
-- detecta. Una FK compuesta sí lo habría cubierto, porque las claves foráneas se
-- verifican también desde el lado referenciado. Es el precio de no tocar la tabla,
-- y es un precio bajo: cambiar la actividad de un plan existente no es una
-- operación normal del negocio.
--
-- SI ALGÚN DÍA MOLESTA: la salida no es agregar columnas sino replicar el trigger
-- sobre Plan_Actividad, rechazando el cambio de id_actividad cuando el plan ya
-- tiene inscripciones con reservas.
CREATE FUNCTION trg_reserva_coherencia_inscripcion() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_act_turno         int;
  v_act_inscripcion   int;
  v_socio_inscripcion int;
  v_nombre_turno      text;
  v_nombre_inscrip    text;
BEGIN
  -- Clase suelta: no hay inscripcion que validar, se paga y se entra.
  IF NEW.id_inscripcion IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT t.id_actividad, a.nombre
    INTO v_act_turno, v_nombre_turno
  FROM "Turno" t
  LEFT JOIN "Actividad" a ON a.id_actividad = t.id_actividad
  WHERE t.id_turno = NEW.id_turno;

  -- El turno o la inscripcion pudieron borrarse en la misma transaccion:
  -- de eso se ocupan las foreign keys, no este trigger.
  IF v_act_turno IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT pa.id_actividad, i.id_socio, a.nombre
    INTO v_act_inscripcion, v_socio_inscripcion, v_nombre_inscrip
  FROM "Inscripcion_Actividad" i
  JOIN "Plan_Actividad" pa ON pa.id_plan_actividad = i.id_plan_actividad
  LEFT JOIN "Actividad" a  ON a.id_actividad = pa.id_actividad
  WHERE i.id_inscripcion = NEW.id_inscripcion;

  IF v_act_inscripcion IS NULL THEN
    RETURN NULL;
  END IF;

  -- 1. Misma actividad.
  IF v_act_turno <> v_act_inscripcion THEN
    RAISE EXCEPTION
      'La inscripcion % es de % y el turno % es de %. Una inscripcion solo sirve para su propia actividad.',
      NEW.id_inscripcion, coalesce(v_nombre_inscrip, 'actividad ' || v_act_inscripcion),
      NEW.id_turno,       coalesce(v_nombre_turno,   'actividad ' || v_act_turno)
      USING ERRCODE = 'check_violation';
  END IF;

  -- 2. Mismo socio.
  IF v_socio_inscripcion <> NEW.id_socio THEN
    RAISE EXCEPTION
      'La inscripcion % pertenece al socio % y la reserva es del socio %. Nadie puede consumir la inscripcion de otro.',
      NEW.id_inscripcion, v_socio_inscripcion, NEW.id_socio
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_reserva_coherente
    AFTER INSERT OR UPDATE OF id_turno, id_inscripcion, id_socio ON "Reserva"
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION trg_reserva_coherencia_inscripcion();


-- =============================================================================
-- FIN DEL ESQUEMA
-- =============================================================================
-- Lo que queda sin resolver, y no es deuda técnica sino decisiones pendientes:
--
--   1. El backend contradice la política de cobro. El docstring "EL SISTEMA
--      INFORMA, NO JUZGA" en asistencia.py registra el ingreso con la cuota
--      vencida. Es un modelo de fiado y choca con "sin membresía activa no hay
--      acceso". Es la contradicción más importante que queda.
--
--   2. La regla de congelamientos solapados está definida pero no implementada.
--      Ver el comentario de la tabla Congelamiento.
--
--   3. Cómo detectar una actividad de acceso libre sin depender del nombre
--      'Musculación'.
--
--   4. Pagos online y derecho de arrepentimiento. NO es una consulta técnica:
--      hay que verificarlo con quien corresponda antes de escribir en los
--      términos que no hay devoluciones.
--
--   5. Faltan CHECK de dominio en varias tablas (montos no negativos, rangos de
--      fechas, porcentajes). Están señalados uno por uno en los COMMENT.
--
--   6. Cuatro columnas siguen siendo varchar libre y deberían ser enum o
--      catálogo: Persona.sexo, Rutina.nivel, Comida.momento y
--      Ejercicio.grupo_muscular.
-- =============================================================================
